@echo off
setlocal EnableExtensions DisableDelayedExpansion

if "%~2"=="" exit /b 2

set "WINPTY_VERSION_FILE=%~1"
set "WINPTY_VERSION_HEADER=%~2"
set "WINPTY_VERSION="

set /p WINPTY_VERSION=<"%WINPTY_VERSION_FILE%" || exit /b 1

>"%WINPTY_VERSION_HEADER%" echo // AUTO-GENERATED BY NMakefile
>>"%WINPTY_VERSION_HEADER%" echo const char GenVersion_Version[] = "%WINPTY_VERSION%";
>>"%WINPTY_VERSION_HEADER%" echo const char GenVersion_Commit[] = "none";
