#!/bin/sh
set -eu

if [ "$#" -ne 1 ]; then
    echo "usage: $0 <output-header>" >&2
    exit 2
fi

output=$1
tmp_dir=${TMPDIR:-/tmp}/remote-exec-cpp-config.$$
tmp_header=$tmp_dir/remote_exec_cpp_config.h
mkdir -p "$tmp_dir"
trap 'rm -rf "$tmp_dir"' EXIT HUP INT TERM

: "${HOST_CXX:=c++}"
: "${PROBE_CPPFLAGS:=}"
: "${PROBE_CXXFLAGS:=-std=c++11 -O2 -Wall -Wextra -pthread}"
: "${PROBE_LDFLAGS:=}"
: "${PROBE_LDLIBS:=-pthread}"

probe() {
    name=$1
    source=$tmp_dir/probe.cpp
    binary=$tmp_dir/probe
    cat > "$source"
    if $HOST_CXX $PROBE_CPPFLAGS $PROBE_CXXFLAGS \
        -o "$binary" "$source" \
        $PROBE_LDFLAGS $PROBE_LDLIBS >/dev/null 2>&1; then
        printf '#define %s 1\n' "$name" >> "$tmp_header"
    else
        printf '#define %s 0\n' "$name" >> "$tmp_header"
    fi
}

cat > "$tmp_header" <<'EOF'
#pragma once

/*
 * Generated by scripts/write_posix_config_header.sh.
 *
 * These macros describe APIs that compiled and linked with the active POSIX
 * toolchain. Keep ABI-runtime lookup separate from this file; this header is
 * for build-time feature selection.
 */
#define REMOTE_EXEC_CPP_POSIX_CONFIG_PROBED 1
EOF

probe REMOTE_EXEC_CPP_HAVE_PTHREAD_CONDATTR_SETCLOCK <<'EOF'
#include <pthread.h>
#include <time.h>
extern "C" int pthread_condattr_setclock(pthread_condattr_t*, clockid_t);
int main() {
    pthread_condattr_t attr;
    (void)attr;
    (void)CLOCK_MONOTONIC;
    return pthread_condattr_setclock(&attr, CLOCK_MONOTONIC);
}
EOF

probe REMOTE_EXEC_CPP_HAVE_POSIX_OPENPT <<'EOF'
#include <fcntl.h>
extern "C" int posix_openpt(int);
int main() {
    return posix_openpt(O_RDWR | O_NOCTTY);
}
EOF

probe REMOTE_EXEC_CPP_HAVE_GRANTPT <<'EOF'
extern "C" int grantpt(int);
int main() {
    return grantpt(-1);
}
EOF

probe REMOTE_EXEC_CPP_HAVE_UNLOCKPT <<'EOF'
extern "C" int unlockpt(int);
int main() {
    return unlockpt(-1);
}
EOF

probe REMOTE_EXEC_CPP_HAVE_PTSNAME <<'EOF'
extern "C" char* ptsname(int);
int main() {
    return ptsname(-1) == 0 ? 0 : 1;
}
EOF

probe REMOTE_EXEC_CPP_HAVE_PTSNAME_R <<'EOF'
#include <cstddef>
#include <stdlib.h>
int main() {
    char buffer[64];
    return ptsname_r(-1, buffer, sizeof(buffer));
}
EOF

probe REMOTE_EXEC_CPP_HAVE_PIPE2 <<'EOF'
#include <fcntl.h>
#include <unistd.h>
int main() {
    int fds[2];
    return pipe2(fds, O_CLOEXEC);
}
EOF

probe REMOTE_EXEC_CPP_HAVE_O_CLOEXEC <<'EOF'
#include <fcntl.h>
int main() {
    return O_CLOEXEC == 0 ? 1 : 0;
}
EOF

probe REMOTE_EXEC_CPP_HAVE_SOCK_CLOEXEC <<'EOF'
#include <sys/socket.h>
int main() {
    return SOCK_CLOEXEC == 0 ? 1 : 0;
}
EOF

probe REMOTE_EXEC_CPP_HAVE_ACCEPT4 <<'EOF'
#include <sys/socket.h>
int main() {
    return accept4(-1, 0, 0, SOCK_CLOEXEC);
}
EOF

probe REMOTE_EXEC_CPP_HAVE_MSG_NOSIGNAL <<'EOF'
#include <sys/socket.h>
int main() {
    return MSG_NOSIGNAL == 0 ? 1 : 0;
}
EOF

probe REMOTE_EXEC_CPP_HAVE_SO_NOSIGPIPE <<'EOF'
#include <sys/socket.h>
int main() {
    return SO_NOSIGPIPE == 0 ? 1 : 0;
}
EOF

mkdir -p "$(dirname "$output")"
if [ -f "$output" ] && cmp -s "$tmp_header" "$output"; then
    exit 0
fi
cp "$tmp_header" "$output"
