BUILD_DIR ?= $(MAKEFILE_DIR)build
OBJ_DIR := $(BUILD_DIR)/obj

COMMON_CPPFLAGS := -I$(MAKEFILE_DIR)include -I$(MAKEFILE_DIR)third_party
TLS ?= auto
OPENSSL_ROOT ?=
OPENSSL_CPPFLAGS ?=
OPENSSL_LDLIBS ?=
OPENSSL_VERSION ?= 3.5.7
OPENSSL_SHA256 ?= a8c0d28a529ca480f9f36cf5792e2cd21984552a3c8e4aa11a24aa31aeac98e8
OPENSSL_URL ?=
OPENSSL_DEPS_DIR ?= $(BUILD_DIR)/deps
OPENSSL_ARCHIVE ?=
OPENSSL_SOURCE_DIR ?=
OPENSSL_INSTALL_DIR ?=
OPENSSL_CONFIGURE_TARGET ?=
OPENSSL_CONFIGURE_OPTIONS ?=
OPENSSL_JOBS ?= 1
OPENSSL_BUILD_MAKE ?= make
OPENSSL_BUILD_MODE ?= default
OPENSSL_XP_VERSION ?= 1.0.2u
OPENSSL_XP_SHA256 ?= ecd0c6ffb493dd06707d38b14bb4d8c2288bb7033735606569d8f90f89669d16
OPENSSL_XP_URL ?= https://www.openssl.org/source/old/1.0.2/openssl-$(OPENSSL_XP_VERSION).tar.gz
ifeq ($(filter $(TLS),auto off openssl),)
$(error unsupported TLS '$(TLS)'; use auto, off, or openssl)
endif
OPENSSL_CANDIDATE_CPPFLAGS := $(if $(OPENSSL_ROOT),-I$(OPENSSL_ROOT)/include) $(OPENSSL_CPPFLAGS)
OPENSSL_CANDIDATE_LDLIBS := $(if $(OPENSSL_LDLIBS),$(OPENSSL_LDLIBS),$(if $(OPENSSL_ROOT),-L$(OPENSSL_ROOT)/lib) -lssl -lcrypto)
DEBUG ?= 0
ifeq ($(filter 1 yes true on,$(DEBUG)),)
MODE_CXXFLAGS := -O2
else
MODE_CXXFLAGS := -O0 -g
endif
BASE_CXXFLAGS := -std=c++11 $(MODE_CXXFLAGS) -Wall -Wextra
PROD_CXXFLAGS ?= $(BASE_CXXFLAGS)
TEST_CXXFLAGS ?= $(BASE_CXXFLAGS)
HOST_TEST_CXXFLAGS := $(TEST_CXXFLAGS)
XP_TEST_CXXFLAGS ?= $(BASE_CXXFLAGS)
DEPFLAGS := -MMD -MP
DEP_FILES :=
TEST_LOG_LEVEL := $(if $(REMOTE_EXEC_LOG),$(REMOTE_EXEC_LOG),$(if $(REMOTE_EXEC_TEST_LOG),$(REMOTE_EXEC_TEST_LOG),off))

SOURCE_PREFIX := $(MAKEFILE_DIR)
include $(MAKEFILE_DIR)mk/sources.mk

cpp_objs = $(patsubst $(MAKEFILE_DIR)%.cpp,$(1)/%.o,$(2))

define run_test
$1: $2
	REMOTE_EXEC_LOG=$(TEST_LOG_LEVEL) $2
endef

prepare-openssl:
	OPENSSL_VERSION="$(OPENSSL_VERSION)" \
	OPENSSL_SHA256="$(OPENSSL_SHA256)" \
	OPENSSL_URL="$(OPENSSL_URL)" \
	OPENSSL_DEPS_DIR="$(OPENSSL_DEPS_DIR)" \
	OPENSSL_ARCHIVE="$(OPENSSL_ARCHIVE)" \
	OPENSSL_SOURCE_DIR="$(OPENSSL_SOURCE_DIR)" \
	OPENSSL_INSTALL_DIR="$(OPENSSL_INSTALL_DIR)" \
	OPENSSL_CONFIGURE_TARGET="$(OPENSSL_CONFIGURE_TARGET)" \
	OPENSSL_CONFIGURE_OPTIONS="$(OPENSSL_CONFIGURE_OPTIONS)" \
	OPENSSL_JOBS="$(OPENSSL_JOBS)" \
	OPENSSL_BUILD_MAKE="$(OPENSSL_BUILD_MAKE)" \
	OPENSSL_BUILD_MODE="$(OPENSSL_BUILD_MODE)" \
	sh "$(MAKEFILE_DIR)scripts/prepare_openssl.sh"

prepare-openssl-xp:
	$(MAKE) prepare-openssl \
		OPENSSL_VERSION="$(OPENSSL_XP_VERSION)" \
		OPENSSL_SHA256="$(OPENSSL_XP_SHA256)" \
		OPENSSL_URL="$(OPENSSL_XP_URL)" \
		OPENSSL_CONFIGURE_TARGET=mingw \
		OPENSSL_CONFIGURE_OPTIONS=no-apps \
		OPENSSL_BUILD_MODE=static-libraries-only

.PHONY: prepare-openssl prepare-openssl-xp
