OPENSSL_ROOT ?=
OPENSSL_CPPFLAGS ?=
OPENSSL_LDLIBS ?=
OPENSSL_VERSION ?= 3.5.7
OPENSSL_SHA256 ?= a8c0d28a529ca480f9f36cf5792e2cd21984552a3c8e4aa11a24aa31aeac98e8
OPENSSL_URL ?=
OPENSSL_DEPS_DIR ?= ${BUILD_DIR}/deps
OPENSSL_ARCHIVE ?=
OPENSSL_SOURCE_DIR ?=
OPENSSL_INSTALL_DIR ?=
OPENSSL_CONFIGURE_TARGET ?=
OPENSSL_CONFIGURE_OPTIONS ?=
OPENSSL_BASE_CONFIGURE_OPTIONS ?= no-shared no-tests
OPENSSL_JOBS ?= 1
OPENSSL_BUILD_MAKE ?= make
OPENSSL_BUILD_MODE ?= default

prepare-openssl:
	OPENSSL_VERSION="${OPENSSL_VERSION}" \
	OPENSSL_SHA256="${OPENSSL_SHA256}" \
	OPENSSL_URL="${OPENSSL_URL}" \
	OPENSSL_DEPS_DIR="${OPENSSL_DEPS_DIR}" \
	OPENSSL_ARCHIVE="${OPENSSL_ARCHIVE}" \
	OPENSSL_SOURCE_DIR="${OPENSSL_SOURCE_DIR}" \
	OPENSSL_INSTALL_DIR="${OPENSSL_INSTALL_DIR}" \
	OPENSSL_CONFIGURE_TARGET="${OPENSSL_CONFIGURE_TARGET}" \
	OPENSSL_CONFIGURE_OPTIONS="${OPENSSL_CONFIGURE_OPTIONS}" \
	OPENSSL_BASE_CONFIGURE_OPTIONS="${OPENSSL_BASE_CONFIGURE_OPTIONS}" \
	OPENSSL_JOBS="${OPENSSL_JOBS}" \
	OPENSSL_BUILD_MAKE="${OPENSSL_BUILD_MAKE}" \
	OPENSSL_BUILD_MODE="${OPENSSL_BUILD_MODE}" \
	sh "${MAKEFILE_DIR}scripts/prepare_openssl.sh"

.PHONY: prepare-openssl
