OPENSSL_ROOT ?=
OPENSSL_CPPFLAGS ?=
OPENSSL_LDLIBS ?=
OPENSSL_VERSION ?= 3.5.7
OPENSSL_SHA256 ?= a8c0d28a529ca480f9f36cf5792e2cd21984552a3c8e4aa11a24aa31aeac98e8
OPENSSL_URL ?=
OPENSSL_DEPS_DIR ?= $(BUILD_DIR)/deps
OPENSSL_ARCHIVE ?=
OPENSSL_SOURCE_DIR ?=
OPENSSL_INSTALL_DIR ?=
OPENSSL_CONFIGURE_TARGET ?=
OPENSSL_CONFIGURE_OPTIONS ?=
OPENSSL_BASE_CONFIGURE_OPTIONS ?= no-shared no-module no-tests no-asm
OPENSSL_JOBS ?= 1
OPENSSL_BUILD_MAKE ?= make
OPENSSL_BUILD_MODE ?= default
OPENSSL_1X_VERSION ?= 1.0.2u
OPENSSL_1X_SHA256 ?= ecd0c6ffb493dd06707d38b14bb4d8c2288bb7033735606569d8f90f89669d16
OPENSSL_1X_URL ?= https://www.openssl.org/source/old/1.0.2/openssl-$(OPENSSL_1X_VERSION).tar.gz

prepare-openssl:
	OPENSSL_VERSION="$(OPENSSL_VERSION)" \
	OPENSSL_SHA256="$(OPENSSL_SHA256)" \
	OPENSSL_URL="$(OPENSSL_URL)" \
	OPENSSL_DEPS_DIR="$(OPENSSL_DEPS_DIR)" \
	OPENSSL_ARCHIVE="$(OPENSSL_ARCHIVE)" \
	OPENSSL_SOURCE_DIR="$(OPENSSL_SOURCE_DIR)" \
	OPENSSL_INSTALL_DIR="$(OPENSSL_INSTALL_DIR)" \
	OPENSSL_CONFIGURE_TARGET="$(OPENSSL_CONFIGURE_TARGET)" \
	OPENSSL_CONFIGURE_OPTIONS="$(OPENSSL_CONFIGURE_OPTIONS)" \
	OPENSSL_BASE_CONFIGURE_OPTIONS="$(OPENSSL_BASE_CONFIGURE_OPTIONS)" \
	OPENSSL_JOBS="$(OPENSSL_JOBS)" \
	OPENSSL_BUILD_MAKE="$(OPENSSL_BUILD_MAKE)" \
	OPENSSL_BUILD_MODE="$(OPENSSL_BUILD_MODE)" \
	sh "$(MAKEFILE_DIR)scripts/prepare_openssl.sh"

prepare-openssl-xp:
	$(MAKE) prepare-openssl \
		OPENSSL_CONFIGURE_TARGET=mingw \
		OPENSSL_CONFIGURE_OPTIONS=no-apps

prepare-openssl-xp-1.0.x:
	$(MAKE) prepare-openssl \
		OPENSSL_VERSION="$(OPENSSL_1X_VERSION)" \
		OPENSSL_SHA256="$(OPENSSL_1X_SHA256)" \
		OPENSSL_URL="$(OPENSSL_1X_URL)" \
		OPENSSL_CONFIGURE_TARGET=mingw \
		OPENSSL_CONFIGURE_OPTIONS=no-apps \
		OPENSSL_BUILD_MODE=static-libraries-only

.PHONY: prepare-openssl prepare-openssl-xp prepare-openssl-xp-1.0.x
