WINDOWS_NATIVE_CXX ?= g++

WINDOWS_NATIVE_PROD_OBJ_DIR := $(OBJ_DIR)/windows-native-prod
WINDOWS_NATIVE_TARGET := $(BUILD_DIR)/remote-exec-daemon-cpp.exe

WINDOWS_NATIVE_PROD_CPPFLAGS := $(COMMON_CPPFLAGS) -DWIN32_LEAN_AND_MEAN
WINDOWS_NATIVE_PROD_CXXFLAGS := $(PROD_CXXFLAGS)
WINDOWS_NATIVE_LDFLAGS ?=
WINDOWS_NATIVE_LDLIBS := -lws2_32

WINDOWS_NATIVE_SRCS := \
	$(BASE_SRCS) \
	$(MAKEFILE_DIR)src/main.cpp \
	$(MAKEFILE_DIR)src/process_session_win32.cpp \
	$(MAKEFILE_DIR)src/console_output.cpp \
	$(MAKEFILE_DIR)src/win32_error.cpp

WINDOWS_NATIVE_OBJS := $(sort $(call cpp_objs,$(WINDOWS_NATIVE_PROD_OBJ_DIR),$(WINDOWS_NATIVE_SRCS)))

DEP_FILES += \
	$(WINDOWS_NATIVE_OBJS:.o=.d)

all-windows-native: $(WINDOWS_NATIVE_TARGET)

$(WINDOWS_NATIVE_TARGET): $(WINDOWS_NATIVE_OBJS)
	mkdir -p $(dir $@)
	$(WINDOWS_NATIVE_CXX) $(WINDOWS_NATIVE_PROD_CXXFLAGS) $(WINDOWS_NATIVE_LDFLAGS) -o $@ $^ $(WINDOWS_NATIVE_LDLIBS)

$(WINDOWS_NATIVE_PROD_OBJ_DIR)/%.o: $(MAKEFILE_DIR)%.cpp
	mkdir -p $(dir $@)
	$(WINDOWS_NATIVE_CXX) $(WINDOWS_NATIVE_PROD_CPPFLAGS) $(WINDOWS_NATIVE_PROD_CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

.PHONY: all-windows-native
