ifndef WINDOWS_GNU_MK_INCLUDED
WINDOWS_GNU_MK_INCLUDED := 1

WINDOWS_NATIVE_TOOLCHAIN := native
WINDOWS_CROSS_TOOLCHAIN := cross
WINDOWS_ARCH_X86 := x86
WINDOWS_ARCH_X64 := x64

WINDOWS_WINVER_NT4 := 0x0400
WINDOWS_WINVER_9X := 0x0400
WINDOWS_WINVER_2000 := 0x0500
WINDOWS_WINVER_XP := 0x0501
WINDOWS_FAMILY_NT := nt
WINDOWS_FAMILY_9X := 9x

WINDOWS_WINSOCK1 := 1
WINDOWS_WINSOCK2 := 2
WINDOWS_CHAR_API_UNICODE := unicode
WINDOWS_CHAR_API_ANSI := ansi

WINDOWS_TOOLCHAIN ?= $(if $(filter Windows_NT,$(OS)),$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_CROSS_TOOLCHAIN))
WINDOWS_WINVER ?= $(WINDOWS_WINVER_XP)
WINDOWS_WIN32_WINNT ?= $(WINDOWS_WINVER)
WINDOWS_FAMILY ?= $(WINDOWS_FAMILY_NT)
WINDOWS_WIN32_WINDOWS ?= $(WINDOWS_WINVER)
WINDOWS_WINSOCK_VERSION ?= $(WINDOWS_WINSOCK2)
WINDOWS_CHAR_API ?= $(WINDOWS_CHAR_API_UNICODE)
WINDOWS_ARCH ?= $(WINDOWS_ARCH_X86)
WINDOWS_WINPTY ?= auto

WINDOWS_COMMON_CPPFLAGS := $(COMMON_CPPFLAGS) -DWIN32_LEAN_AND_MEAN
WINDOWS_TEST_CXXFLAGS := $(TEST_CXXFLAGS)
WINDOWS_PROD_CXXFLAGS := $(PROD_CXXFLAGS)

WINDOWS_CROSS_CXX_X86 ?= i686-w64-mingw32-g++
WINDOWS_CROSS_CXX_X64 ?= x86_64-w64-mingw32-g++
WINDOWS_CROSS_CXX ?= $(if $(filter $(WINDOWS_ARCH_X64),$(WINDOWS_ARCH)),$(WINDOWS_CROSS_CXX_X64),$(WINDOWS_CROSS_CXX_X86))
WINDOWS_NATIVE_CXX ?= g++
WINE ?= wine

ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_CROSS_TOOLCHAIN))
WINDOWS_CXX ?= $(WINDOWS_CROSS_CXX)
WINDOWS_TOOLCHAIN_LDFLAGS_DEFAULT := -static-libgcc -static-libstdc++
WINDOWS_TOOLCHAIN_BUILD_TAG := windows-cross
ifeq ($(OS),Windows_NT)
WINDOWS_TEST_RUNNER ?=
else
WINDOWS_TEST_RUNNER ?= $(WINE)
endif
endif

ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_NATIVE_TOOLCHAIN))
ifeq ($(OS),Windows_NT)
WINDOWS_CXX ?= $(WINDOWS_NATIVE_CXX)
WINDOWS_TOOLCHAIN_LDFLAGS_DEFAULT :=
WINDOWS_TOOLCHAIN_BUILD_TAG := windows-native
WINDOWS_TEST_RUNNER ?=
else
$(error WINDOWS_TOOLCHAIN=native requires a Windows GNU host environment)
endif
endif

ifndef WINDOWS_TOOLCHAIN_BUILD_TAG
$(error unsupported WINDOWS_TOOLCHAIN '$(WINDOWS_TOOLCHAIN)')
endif

ifeq ($(filter $(WINDOWS_WINSOCK_VERSION),$(WINDOWS_WINSOCK1) $(WINDOWS_WINSOCK2)),)
$(error unsupported WINDOWS_WINSOCK_VERSION '$(WINDOWS_WINSOCK_VERSION)'; use 1 or 2)
endif

ifeq ($(filter $(WINDOWS_CHAR_API),$(WINDOWS_CHAR_API_UNICODE) $(WINDOWS_CHAR_API_ANSI)),)
$(error unsupported WINDOWS_CHAR_API '$(WINDOWS_CHAR_API)'; use unicode or ansi)
endif

ifeq ($(filter $(WINDOWS_ARCH),$(WINDOWS_ARCH_X86) $(WINDOWS_ARCH_X64)),)
$(error unsupported WINDOWS_ARCH '$(WINDOWS_ARCH)'; use x86 or x64)
endif

ifeq ($(filter $(WINDOWS_FAMILY),$(WINDOWS_FAMILY_NT) $(WINDOWS_FAMILY_9X)),)
$(error unsupported WINDOWS_FAMILY '$(WINDOWS_FAMILY)'; use nt or 9x)
endif

ifeq ($(WINDOWS_FAMILY),$(WINDOWS_FAMILY_9X))
ifeq ($(WINDOWS_ARCH),$(WINDOWS_ARCH_X64))
$(error WINDOWS_FAMILY=9x requires WINDOWS_ARCH=x86)
endif
ifneq ($(WINDOWS_CHAR_API),$(WINDOWS_CHAR_API_ANSI))
$(error WINDOWS_FAMILY=9x requires WINDOWS_CHAR_API=ansi)
endif
endif

ifeq ($(filter $(WINDOWS_WINPTY),auto on off),)
$(error unsupported WINDOWS_WINPTY '$(WINDOWS_WINPTY)'; use auto, on, or off)
endif

WINDOWS_WINVER_HEX_TAG := $(patsubst 0x%,%,$(patsubst 0X%,%,$(WINDOWS_WINVER)))
WINDOWS_WINVER_LABEL := winver$(WINDOWS_WINVER_HEX_TAG)
ifeq ($(WINDOWS_FAMILY),$(WINDOWS_FAMILY_9X))
WINDOWS_WINVER_LABEL := 9x
else
ifeq ($(WINDOWS_WINVER),$(WINDOWS_WINVER_NT4))
WINDOWS_WINVER_LABEL := nt4
endif
ifeq ($(WINDOWS_WINVER),$(WINDOWS_WINVER_2000))
WINDOWS_WINVER_LABEL := 2000
endif
ifeq ($(WINDOWS_WINVER),$(WINDOWS_WINVER_XP))
WINDOWS_WINVER_LABEL := xp
endif
endif
WINDOWS_WS_TAG := ws$(WINDOWS_WINSOCK_VERSION)
WINDOWS_CHAR_API_TAG := $(WINDOWS_CHAR_API)
WINDOWS_ARCH_BUILD_TAG := $(if $(filter $(WINDOWS_ARCH_X64),$(WINDOWS_ARCH)),-x64,)
WINDOWS_ARCH_BINARY_PREFIX := $(if $(filter $(WINDOWS_ARCH_X64),$(WINDOWS_ARCH)),x64-,)
ifeq ($(WINDOWS_CHAR_API),$(WINDOWS_CHAR_API_UNICODE))
WINDOWS_CHAR_API_CPPFLAGS := -DUNICODE -D_UNICODE
WINDOWS_CHAR_API_TAG :=
else
WINDOWS_CHAR_API_CPPFLAGS := -DREMOTE_EXEC_CPP_WINDOWS_ANSI_API
endif

WINDOWS_VARIANT_AXIS_TAG := $(WINDOWS_WINVER_LABEL)-$(WINDOWS_WS_TAG)$(if $(WINDOWS_CHAR_API_TAG),-$(WINDOWS_CHAR_API_TAG))

ifeq ($(WINDOWS_FAMILY),$(WINDOWS_FAMILY_9X))
WINDOWS_VARIANT_VERSION_CPPFLAGS := -DWINVER=$(WINDOWS_WINVER) -D_WIN32_WINNT=$(WINDOWS_WIN32_WINNT) -D_WIN32_WINDOWS=$(WINDOWS_WIN32_WINDOWS) -D_CHICAGO_
else
WINDOWS_VARIANT_VERSION_CPPFLAGS := -DWINVER=$(WINDOWS_WINVER) -D_WIN32_WINNT=$(WINDOWS_WIN32_WINNT)
endif
WINDOWS_VARIANT_EXTRA_CPPFLAGS :=
WINDOWS_VARIANT_LDLIBS :=
WINDOWS_VARIANT_EXTRA_TEST_CASES :=
WINDOWS_VARIANT_BUILD_ARTIFACTS :=
WINDOWS_VARIANT_RUNTIME_ARTIFACTS :=

WINDOWS_WINPTY_AUTO_WINVERS := $(WINDOWS_WINVER_NT4) $(WINDOWS_WINVER_2000) $(WINDOWS_WINVER_XP)
ifeq ($(WINDOWS_CHAR_API),$(WINDOWS_CHAR_API_ANSI))
WINDOWS_WINPTY_AUTO_ENABLED := 0
else
WINDOWS_WINPTY_AUTO_ENABLED := $(if $(filter $(WINDOWS_WINVER),$(WINDOWS_WINPTY_AUTO_WINVERS)),1,0)
endif
WINDOWS_WINPTY_ENABLED := $(if $(filter $(WINDOWS_WINPTY),on),1,$(if $(filter $(WINDOWS_WINPTY),off),0,$(WINDOWS_WINPTY_AUTO_ENABLED)))

WINDOWS_VARIANT_BUILD_TAG := $(WINDOWS_TOOLCHAIN_BUILD_TAG)$(WINDOWS_ARCH_BUILD_TAG)-winver$(WINDOWS_WINVER_HEX_TAG)-$(WINDOWS_WS_TAG)$(if $(WINDOWS_CHAR_API_TAG),-$(WINDOWS_CHAR_API_TAG))
ifeq ($(WINDOWS_FAMILY),$(WINDOWS_FAMILY_9X))
WINDOWS_VARIANT_BUILD_TAG := $(WINDOWS_TOOLCHAIN_BUILD_TAG)$(WINDOWS_ARCH_BUILD_TAG)-win9x-winver$(WINDOWS_WINVER_HEX_TAG)-$(WINDOWS_WS_TAG)$(if $(WINDOWS_CHAR_API_TAG),-$(WINDOWS_CHAR_API_TAG))
endif

WINPTY_VERSION_HEADER := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-winpty/gen/GenVersion.h
WINPTY_OBJ_DIR := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-winpty
WINPTY_LIB_OBJ_DIR := $(WINPTY_OBJ_DIR)/libwinpty
WINPTY_AGENT_OBJ_DIR := $(WINPTY_OBJ_DIR)/agent
WINPTY_STATIC_LIB := $(WINPTY_OBJ_DIR)/libwinpty.a
WINPTY_AGENT_EXE := $(BUILD_DIR)/winpty-agent.exe
WINPTY_LIB_OBJECTS := $(addprefix $(WINPTY_LIB_OBJ_DIR)/,$(addsuffix .o,$(WINPTY_LIBWINPTY_STEMS)))
WINPTY_AGENT_OBJECTS := $(addprefix $(WINPTY_AGENT_OBJ_DIR)/,$(addsuffix .o,$(WINPTY_AGENT_STEMS)))
WINDOWS_AR ?= $(shell $(WINDOWS_CXX) -print-prog-name=ar)
WINDOWS_WINPTY_INCLUDE_CPPFLAGS := -I$(WINPTY_VENDOR_SRC_DIR)/include -I$(WINPTY_VENDOR_SRC_DIR) -I$(dir $(WINPTY_VERSION_HEADER))
WINDOWS_WINPTY_VARIANT_CPPFLAGS := -DREMOTE_EXEC_CPP_HAS_WINPTY -DWINPTY_STATIC $(WINDOWS_WINPTY_INCLUDE_CPPFLAGS)
WINDOWS_WINPTY_LDLIBS := $(WINPTY_STATIC_LIB) -ladvapi32 -lshell32 -luser32
WINDOWS_WINPTY_COMMON_CPPFLAGS := $(WINDOWS_VARIANT_VERSION_CPPFLAGS) -DREMOTE_EXEC_CPP_HAS_WINPTY -DNOMINMAX -DUNICODE -D_UNICODE $(WINDOWS_PROD_CXXFLAGS) $(DEPFLAGS) $(WINDOWS_WINPTY_INCLUDE_CPPFLAGS)

ifeq ($(WINDOWS_WINSOCK_VERSION),$(WINDOWS_WINSOCK1))
WINDOWS_VARIANT_EXTRA_CPPFLAGS += -DREMOTE_EXEC_CPP_WINSOCK1
WINDOWS_VARIANT_LDLIBS += -lwsock32
WINDOWS_VARIANT_EXTRA_TEST_CASES += WINSOCK1_SOCKET_BACKEND
else
WINDOWS_VARIANT_LDLIBS += -lws2_32
endif

ifeq ($(WINDOWS_WINPTY_ENABLED),1)
WINDOWS_VARIANT_EXTRA_CPPFLAGS += $(WINDOWS_WINPTY_VARIANT_CPPFLAGS)
WINDOWS_VARIANT_LDLIBS += $(WINDOWS_WINPTY_LDLIBS)
WINDOWS_VARIANT_BUILD_ARTIFACTS += $(WINPTY_STATIC_LIB)
WINDOWS_VARIANT_RUNTIME_ARTIFACTS += $(WINPTY_AGENT_EXE)
endif

ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_NATIVE_TOOLCHAIN))
WINDOWS_VARIANT_BINARY_TAG := native-$(WINDOWS_ARCH_BINARY_PREFIX)$(WINDOWS_VARIANT_AXIS_TAG)
else
WINDOWS_VARIANT_BINARY_TAG := $(WINDOWS_ARCH_BINARY_PREFIX)$(WINDOWS_VARIANT_AXIS_TAG)
endif

WINDOWS_LDFLAGS ?= $(WINDOWS_TOOLCHAIN_LDFLAGS_DEFAULT)
WINDOWS_TEST_ENV := REMOTE_EXEC_LOG=$(TEST_LOG_LEVEL) $(WINDOWS_TEST_RUNNER)
WINDOWS_VARIANT_PROD_OBJ_DIR := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-prod
WINDOWS_VARIANT_TEST_OBJ_DIR := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-test
WINDOWS_VARIANT_TARGET := $(BUILD_DIR)/remote-exec-daemon-cpp-$(WINDOWS_VARIANT_BINARY_TAG).exe
WINDOWS_VARIANT_PROD_CPPFLAGS := $(WINDOWS_COMMON_CPPFLAGS) $(WINDOWS_CHAR_API_CPPFLAGS) $(WINDOWS_VARIANT_VERSION_CPPFLAGS) $(WINDOWS_VARIANT_EXTRA_CPPFLAGS)
WINDOWS_VARIANT_TEST_CPPFLAGS := $(WINDOWS_COMMON_CPPFLAGS) $(WINDOWS_CHAR_API_CPPFLAGS) $(WINDOWS_VARIANT_VERSION_CPPFLAGS) -DREMOTE_EXEC_CPP_TESTING $(WINDOWS_VARIANT_EXTRA_CPPFLAGS)

DEP_FILES += $(WINPTY_LIB_OBJECTS:.o=.d) $(WINPTY_AGENT_OBJECTS:.o=.d)

WINDOWS_VARIANT_SRCS := $(WINDOWS_DAEMON_SRCS)
WINDOWS_VARIANT_OBJS := $(sort $(call cpp_objs,$(WINDOWS_VARIANT_PROD_OBJ_DIR),$(WINDOWS_VARIANT_SRCS)))

WINDOWS_COMMON_TEST_CASES := \
	BASIC_MUTEX \
	CONSOLE_OUTPUT \
	PATCH \
	SESSION_STORE \
	SERVER_STREAMING \
	TRANSFER \
	CONFIG \
	HTTP_REQUEST \
	SERVER_TRANSPORT \
	CONNECTION_MANAGER \
	SERVER_ROUTES_COMMON \
	SERVER_ROUTES \
	SERVER_RUNTIME \
	SANDBOX \
	PORT_TUNNEL_FRAME

WINDOWS_VARIANT_TEST_CASES := $(WINDOWS_COMMON_TEST_CASES) $(WINDOWS_VARIANT_EXTRA_TEST_CASES)

WINDOWS_TEST_CASE_BASIC_MUTEX_NAME := basic-mutex
WINDOWS_TEST_CASE_BASIC_MUTEX_BASE := test_basic_mutex
WINDOWS_TEST_CASE_BASIC_MUTEX_SRCS := $(WINDOWS_BASIC_MUTEX_TEST_SRCS)

WINDOWS_TEST_CASE_CONSOLE_OUTPUT_NAME := console-output
WINDOWS_TEST_CASE_CONSOLE_OUTPUT_BASE := test_console_output
WINDOWS_TEST_CASE_CONSOLE_OUTPUT_SRCS := $(WINDOWS_CONSOLE_OUTPUT_TEST_SRCS)

WINDOWS_TEST_CASE_PATCH_NAME := patch
WINDOWS_TEST_CASE_PATCH_BASE := test_patch
WINDOWS_TEST_CASE_PATCH_SRCS := $(WINDOWS_PATCH_TEST_SRCS)

WINDOWS_TEST_CASE_SESSION_STORE_NAME := session-store
WINDOWS_TEST_CASE_SESSION_STORE_BASE := test_session_store
WINDOWS_TEST_CASE_SESSION_STORE_SRCS := $(WINDOWS_SESSION_STORE_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_STREAMING_NAME := server-streaming
WINDOWS_TEST_CASE_SERVER_STREAMING_BASE := test_server_streaming
WINDOWS_TEST_CASE_SERVER_STREAMING_SRCS := $(WINDOWS_SERVER_STREAMING_SRCS)

WINDOWS_TEST_CASE_TRANSFER_NAME := transfer
WINDOWS_TEST_CASE_TRANSFER_BASE := test_transfer
WINDOWS_TEST_CASE_TRANSFER_SRCS := $(WINDOWS_TRANSFER_TEST_SRCS)

WINDOWS_TEST_CASE_CONFIG_NAME := config
WINDOWS_TEST_CASE_CONFIG_BASE := test_config
WINDOWS_TEST_CASE_CONFIG_SRCS := $(WINDOWS_CONFIG_TEST_SRCS)

WINDOWS_TEST_CASE_HTTP_REQUEST_NAME := http-request
WINDOWS_TEST_CASE_HTTP_REQUEST_BASE := test_http_request
WINDOWS_TEST_CASE_HTTP_REQUEST_SRCS := $(HOST_HTTP_REQUEST_SRCS)

WINDOWS_TEST_CASE_SERVER_TRANSPORT_NAME := server-transport
WINDOWS_TEST_CASE_SERVER_TRANSPORT_BASE := test_server_transport
WINDOWS_TEST_CASE_SERVER_TRANSPORT_SRCS := $(WINDOWS_SERVER_TRANSPORT_TEST_SRCS)

WINDOWS_TEST_CASE_CONNECTION_MANAGER_NAME := connection-manager
WINDOWS_TEST_CASE_CONNECTION_MANAGER_BASE := test_connection_manager
WINDOWS_TEST_CASE_CONNECTION_MANAGER_SRCS := $(WINDOWS_CONNECTION_MANAGER_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_ROUTES_COMMON_NAME := server-routes-common
WINDOWS_TEST_CASE_SERVER_ROUTES_COMMON_BASE := test_server_routes_common
WINDOWS_TEST_CASE_SERVER_ROUTES_COMMON_SRCS := $(WINDOWS_SERVER_ROUTES_COMMON_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_ROUTES_NAME := server-routes
WINDOWS_TEST_CASE_SERVER_ROUTES_BASE := test_server_routes
WINDOWS_TEST_CASE_SERVER_ROUTES_SRCS := $(WINDOWS_SERVER_ROUTES_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_RUNTIME_NAME := server-runtime
WINDOWS_TEST_CASE_SERVER_RUNTIME_BASE := test_server_runtime
WINDOWS_TEST_CASE_SERVER_RUNTIME_SRCS := $(WINDOWS_SERVER_RUNTIME_TEST_SRCS)

WINDOWS_TEST_CASE_SANDBOX_NAME := sandbox
WINDOWS_TEST_CASE_SANDBOX_BASE := test_sandbox
WINDOWS_TEST_CASE_SANDBOX_SRCS := $(WINDOWS_SANDBOX_TEST_SRCS)

WINDOWS_TEST_CASE_PORT_TUNNEL_FRAME_NAME := port-tunnel-frame
WINDOWS_TEST_CASE_PORT_TUNNEL_FRAME_BASE := test_port_tunnel_frame
WINDOWS_TEST_CASE_PORT_TUNNEL_FRAME_SRCS := $(HOST_PORT_TUNNEL_FRAME_SRCS)

WINDOWS_TEST_CASE_WINSOCK1_SOCKET_BACKEND_NAME := winsock1-socket-backend
WINDOWS_TEST_CASE_WINSOCK1_SOCKET_BACKEND_BASE := test_winsock1_socket_backend
WINDOWS_TEST_CASE_WINSOCK1_SOCKET_BACKEND_SRCS := $(WINDOWS_WINSOCK1_SOCKET_BACKEND_TEST_SRCS)

windows_test_case_bin = $(BUILD_DIR)/$(WINDOWS_TEST_CASE_$1_BASE)-$(WINDOWS_VARIANT_BINARY_TAG).exe
windows_test_case_phony = test-windows-$(WINDOWS_TEST_CASE_$1_NAME)

define define_windows_test_case
WINDOWS_TEST_CASE_$1_BIN := $(call windows_test_case_bin,$1)
WINDOWS_TEST_CASE_$1_OBJS := $(sort $(call cpp_objs,$(WINDOWS_VARIANT_TEST_OBJ_DIR),$(WINDOWS_TEST_CASE_$1_SRCS)))
DEP_FILES += $$(WINDOWS_TEST_CASE_$1_OBJS:.o=.d)

$(call windows_test_case_phony,$1): $$(WINDOWS_TEST_CASE_$1_BIN) $(WINDOWS_VARIANT_RUNTIME_ARTIFACTS)
	$$(WINDOWS_TEST_ENV) $$(WINDOWS_TEST_CASE_$1_BIN)

$$(WINDOWS_TEST_CASE_$1_BIN): $$(WINDOWS_TEST_CASE_$1_OBJS) $(WINDOWS_VARIANT_BUILD_ARTIFACTS) $(WINDOWS_VARIANT_RUNTIME_ARTIFACTS)
	mkdir -p $$(dir $$@)
	$$(WINDOWS_CXX) $$(WINDOWS_TEST_CXXFLAGS) $$(WINDOWS_LDFLAGS) -o $$@ $$(WINDOWS_TEST_CASE_$1_OBJS) $$(WINDOWS_VARIANT_LDLIBS)
endef

$(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(eval $(call define_windows_test_case,$(test))))

WINDOWS_VARIANT_TEST_BINS := $(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(call windows_test_case_bin,$(test)))
WINDOWS_VARIANT_TEST_PHONIES := $(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(call windows_test_case_phony,$(test)))
DEP_FILES += $(WINDOWS_VARIANT_OBJS:.o=.d)

define run_windows_variant_tests
$(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(WINDOWS_TEST_ENV) $(call windows_test_case_bin,$(test))
)
endef

all-windows: $(WINDOWS_VARIANT_TARGET)

$(WINDOWS_VARIANT_TARGET): $(WINDOWS_VARIANT_OBJS) $(WINDOWS_VARIANT_BUILD_ARTIFACTS) $(WINDOWS_VARIANT_RUNTIME_ARTIFACTS)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_PROD_CXXFLAGS) $(WINDOWS_LDFLAGS) -o $@ $(WINDOWS_VARIANT_OBJS) $(WINDOWS_VARIANT_LDLIBS)

$(WINPTY_VERSION_HEADER): $(WINPTY_VENDOR_DIR)/VERSION.txt
	mkdir -p $(dir $@)
	printf '%s\n' '// AUTO-GENERATED BY mk/windows-gnu.mk' > $@
	printf 'const char GenVersion_Version[] = "%s";\n' "$$(tr -d '\r\n' < $<)" >> $@
	printf 'const char GenVersion_Commit[] = "none";\n' >> $@

$(WINPTY_LIB_OBJ_DIR)/%.o: $(WINPTY_VENDOR_SRC_DIR)/%.cc $(WINPTY_VERSION_HEADER)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_WINPTY_COMMON_CPPFLAGS) -DWINPTY_STATIC -c -o $@ $<

$(WINPTY_AGENT_OBJ_DIR)/%.o: $(WINPTY_VENDOR_SRC_DIR)/%.cc $(WINPTY_VERSION_HEADER)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_WINPTY_COMMON_CPPFLAGS) -DWINPTY_AGENT_ASSERT -c -o $@ $<

$(WINPTY_STATIC_LIB): $(WINPTY_LIB_OBJECTS)
	mkdir -p $(dir $@)
	$(WINDOWS_AR) rcs $@ $^

$(WINPTY_AGENT_EXE): $(WINPTY_AGENT_OBJECTS)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_PROD_CXXFLAGS) $(WINDOWS_LDFLAGS) -o $@ $^ -ladvapi32 -lshell32 -luser32

$(WINDOWS_VARIANT_PROD_OBJ_DIR)/%.o: $(MAKEFILE_DIR)%.cpp
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_VARIANT_PROD_CPPFLAGS) $(WINDOWS_PROD_CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

$(WINDOWS_VARIANT_TEST_OBJ_DIR)/%.o: $(MAKEFILE_DIR)%.cpp
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_VARIANT_TEST_CPPFLAGS) $(WINDOWS_TEST_CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

test-windows: $(WINDOWS_VARIANT_TEST_BINS)
	$(run_windows_variant_tests)

check-windows: all-windows test-windows

define define_windows_variant_alias
$1:
	$$(MAKE) $2 WINDOWS_TOOLCHAIN=$3 WINDOWS_WINVER=$4 WINDOWS_WIN32_WINNT=$5 WINDOWS_WINSOCK_VERSION=$6 WINDOWS_CHAR_API=$7 WINDOWS_FAMILY=$8 WINDOWS_WIN32_WINDOWS=$9 WINDOWS_ARCH=$(10) BUILD_DIR=$$(BUILD_DIR)
endef

define define_windows_variant_alias_bundle
$(foreach alias_name,$1,$(eval $(call define_windows_variant_alias,all-windows-$(alias_name),all-windows,$2,$3,$4,$5,$6,$7,$8,$9)))
$(foreach alias_name,$1,$(eval $(call define_windows_variant_alias,test-windows-$(alias_name),test-windows,$2,$3,$4,$5,$6,$7,$8,$9)))
$(foreach alias_name,$1,$(eval $(call define_windows_variant_alias,check-windows-$(alias_name),check-windows,$2,$3,$4,$5,$6,$7,$8,$9)))
endef

WINDOWS_NT4_WS1_ALIAS_NAMES := nt4-ws1
WINDOWS_NT4_WS2_ALIAS_NAMES := nt4-ws2
WINDOWS_2000_ALIAS_NAMES := 2000 2000-ws2
WINDOWS_XP_ALIAS_NAMES := xp xp-ws2
WINDOWS_X64_ALIAS_NAMES := x64 x64-ws2
WINDOWS_NATIVE_ALIAS_NAMES := native
WINDOWS_NT4_WS1_ANSI_ALIAS_NAMES := nt4-ws1-ansi
WINDOWS_XP_ANSI_ALIAS_NAMES := xp-ansi xp-ws2-ansi
WINDOWS_9X_WS1_ANSI_ALIAS_NAMES := 9x-ws1-ansi
WINDOWS_9X_WS2_ANSI_ALIAS_NAMES := 9x-ws2-ansi

$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_NT4_WS1_ALIAS_NAMES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK1),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_NT4),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_NT4_WS2_ALIAS_NAMES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_NT4),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_2000_ALIAS_NAMES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_2000),$(WINDOWS_WINVER_2000),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_2000),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_XP_ALIAS_NAMES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_XP),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_X64_ALIAS_NAMES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_XP),$(WINDOWS_ARCH_X64)))
$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_NATIVE_ALIAS_NAMES),$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_XP),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_NT4_WS1_ANSI_ALIAS_NAMES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK1),$(WINDOWS_CHAR_API_ANSI),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_NT4),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_XP_ANSI_ALIAS_NAMES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_ANSI),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_XP),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_9X_WS1_ANSI_ALIAS_NAMES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_9X),$(WINDOWS_WINVER_9X),$(WINDOWS_WINSOCK1),$(WINDOWS_CHAR_API_ANSI),$(WINDOWS_FAMILY_9X),$(WINDOWS_WINVER_9X),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_variant_alias_bundle,$(WINDOWS_9X_WS2_ANSI_ALIAS_NAMES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_9X),$(WINDOWS_WINVER_9X),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_ANSI),$(WINDOWS_FAMILY_9X),$(WINDOWS_WINVER_9X),$(WINDOWS_ARCH_X86)))

define define_windows_variant_test_alias
$1:
	$$(MAKE) $2 WINDOWS_TOOLCHAIN=$3 WINDOWS_WINVER=$4 WINDOWS_WIN32_WINNT=$5 WINDOWS_WINSOCK_VERSION=$6 WINDOWS_CHAR_API=$7 WINDOWS_FAMILY=$8 WINDOWS_WIN32_WINDOWS=$9 WINDOWS_ARCH=$(10) BUILD_DIR=$$(BUILD_DIR)
endef

define define_windows_named_test_aliases
$(foreach test,$2,$(eval $(call define_windows_variant_test_alias,test-windows-$1-$(WINDOWS_TEST_CASE_$(test)_NAME),$(call windows_test_case_phony,$(test)),$3,$4,$5,$6,$7,$8,$9,$(10))))
endef

$(eval $(call define_windows_named_test_aliases,xp,$(WINDOWS_COMMON_TEST_CASES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_XP),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_named_test_aliases,2000,$(WINDOWS_COMMON_TEST_CASES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_2000),$(WINDOWS_WINVER_2000),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_2000),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_named_test_aliases,x64,$(WINDOWS_COMMON_TEST_CASES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_XP),$(WINDOWS_ARCH_X64)))
$(eval $(call define_windows_named_test_aliases,native,$(WINDOWS_COMMON_TEST_CASES),$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_XP),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_named_test_aliases,nt4-ws1,$(WINDOWS_COMMON_TEST_CASES) WINSOCK1_SOCKET_BACKEND,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK1),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_NT4),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_named_test_aliases,nt4-ws2,$(WINDOWS_COMMON_TEST_CASES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_UNICODE),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_NT4),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_named_test_aliases,xp-ansi,$(WINDOWS_COMMON_TEST_CASES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_ANSI),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_XP),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_named_test_aliases,nt4-ws1-ansi,$(WINDOWS_COMMON_TEST_CASES) WINSOCK1_SOCKET_BACKEND,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK1),$(WINDOWS_CHAR_API_ANSI),$(WINDOWS_FAMILY_NT),$(WINDOWS_WINVER_NT4),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_named_test_aliases,9x-ws1-ansi,$(WINDOWS_COMMON_TEST_CASES) WINSOCK1_SOCKET_BACKEND,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_9X),$(WINDOWS_WINVER_9X),$(WINDOWS_WINSOCK1),$(WINDOWS_CHAR_API_ANSI),$(WINDOWS_FAMILY_9X),$(WINDOWS_WINVER_9X),$(WINDOWS_ARCH_X86)))
$(eval $(call define_windows_named_test_aliases,9x-ws2-ansi,$(WINDOWS_COMMON_TEST_CASES),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_9X),$(WINDOWS_WINVER_9X),$(WINDOWS_WINSOCK2),$(WINDOWS_CHAR_API_ANSI),$(WINDOWS_FAMILY_9X),$(WINDOWS_WINVER_9X),$(WINDOWS_ARCH_X86)))

windows_named_test_alias_phonies = $(foreach test,$2,test-windows-$1-$(WINDOWS_TEST_CASE_$(test)_NAME))
windows_variant_alias_phonies = $(foreach alias_name,$1,all-windows-$(alias_name) test-windows-$(alias_name) check-windows-$(alias_name))

WINDOWS_XP_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,xp,$(WINDOWS_COMMON_TEST_CASES))
WINDOWS_2000_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,2000,$(WINDOWS_COMMON_TEST_CASES))
WINDOWS_X64_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,x64,$(WINDOWS_COMMON_TEST_CASES))
WINDOWS_NT4_WS1_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,nt4-ws1,$(WINDOWS_COMMON_TEST_CASES) WINSOCK1_SOCKET_BACKEND)
WINDOWS_NT4_WS2_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,nt4-ws2,$(WINDOWS_COMMON_TEST_CASES))
WINDOWS_NATIVE_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,native,$(WINDOWS_COMMON_TEST_CASES))
WINDOWS_XP_ANSI_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,xp-ansi,$(WINDOWS_COMMON_TEST_CASES))
WINDOWS_NT4_WS1_ANSI_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,nt4-ws1-ansi,$(WINDOWS_COMMON_TEST_CASES) WINSOCK1_SOCKET_BACKEND)
WINDOWS_9X_WS1_ANSI_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,9x-ws1-ansi,$(WINDOWS_COMMON_TEST_CASES) WINSOCK1_SOCKET_BACKEND)
WINDOWS_9X_WS2_ANSI_TEST_ALIAS_PHONIES := $(call windows_named_test_alias_phonies,9x-ws2-ansi,$(WINDOWS_COMMON_TEST_CASES))
WINDOWS_VARIANT_ALIAS_PHONIES := \
	$(call windows_variant_alias_phonies,$(WINDOWS_NT4_WS1_ALIAS_NAMES)) \
	$(call windows_variant_alias_phonies,$(WINDOWS_NT4_WS2_ALIAS_NAMES)) \
	$(call windows_variant_alias_phonies,$(WINDOWS_2000_ALIAS_NAMES)) \
	$(call windows_variant_alias_phonies,$(WINDOWS_XP_ALIAS_NAMES)) \
	$(call windows_variant_alias_phonies,$(WINDOWS_X64_ALIAS_NAMES)) \
	$(call windows_variant_alias_phonies,$(WINDOWS_NATIVE_ALIAS_NAMES)) \
	$(call windows_variant_alias_phonies,$(WINDOWS_NT4_WS1_ANSI_ALIAS_NAMES)) \
	$(call windows_variant_alias_phonies,$(WINDOWS_XP_ANSI_ALIAS_NAMES)) \
	$(call windows_variant_alias_phonies,$(WINDOWS_9X_WS1_ANSI_ALIAS_NAMES)) \
	$(call windows_variant_alias_phonies,$(WINDOWS_9X_WS2_ANSI_ALIAS_NAMES))

.PHONY: \
	all-windows \
	test-windows \
	check-windows \
	$(WINDOWS_VARIANT_ALIAS_PHONIES) \
	$(WINDOWS_VARIANT_TEST_PHONIES) \
	$(WINDOWS_XP_TEST_ALIAS_PHONIES) \
	$(WINDOWS_2000_TEST_ALIAS_PHONIES) \
	$(WINDOWS_X64_TEST_ALIAS_PHONIES) \
	$(WINDOWS_NT4_WS1_TEST_ALIAS_PHONIES) \
	$(WINDOWS_NT4_WS2_TEST_ALIAS_PHONIES) \
	$(WINDOWS_NATIVE_TEST_ALIAS_PHONIES) \
	$(WINDOWS_XP_ANSI_TEST_ALIAS_PHONIES) \
	$(WINDOWS_NT4_WS1_ANSI_TEST_ALIAS_PHONIES) \
	$(WINDOWS_9X_WS1_ANSI_TEST_ALIAS_PHONIES) \
	$(WINDOWS_9X_WS2_ANSI_TEST_ALIAS_PHONIES)

endif
