WINDOWS_CXX ?= i686-w64-mingw32-g++
WINE ?= wine
ifeq ($(OS),Windows_NT)
WINDOWS_TEST_RUNNER :=
else
WINDOWS_TEST_RUNNER ?= $(WINE)
endif

WINDOWS_COMMON_CPPFLAGS := $(COMMON_CPPFLAGS) -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE
WINDOWS_TEST_CXXFLAGS := $(XP_TEST_CXXFLAGS)
WINDOWS_PROD_CXXFLAGS := $(PROD_CXXFLAGS)
WINDOWS_LDFLAGS := -static-libgcc -static-libstdc++

WINDOWS_WINSOCK1_PROD_OBJ_DIR := $(OBJ_DIR)/windows-winsock1-prod
WINDOWS_WINSOCK1_TEST_OBJ_DIR := $(OBJ_DIR)/windows-winsock1-test
WINDOWS_WINSOCK1_TARGET := $(BUILD_DIR)/remote-exec-daemon-cpp-winsock1.exe
WINDOWS_WINSOCK1_VERSION_CPPFLAGS := -DWINVER=0x0400 -D_WIN32_WINNT=0x0400
WINDOWS_WINSOCK1_CPPFLAGS := -DREMOTE_EXEC_CPP_WINSOCK1
WINDOWS_WINSOCK1_PROD_CPPFLAGS := $(WINDOWS_COMMON_CPPFLAGS) $(WINDOWS_WINSOCK1_VERSION_CPPFLAGS) $(WINDOWS_WINSOCK1_CPPFLAGS)
WINDOWS_WINSOCK1_TEST_CPPFLAGS := $(WINDOWS_COMMON_CPPFLAGS) $(WINDOWS_WINSOCK1_VERSION_CPPFLAGS) -DREMOTE_EXEC_CPP_TESTING $(WINDOWS_WINSOCK1_CPPFLAGS)
WINDOWS_WINSOCK1_LDLIBS := -lwsock32

WINSOCK1_SOCKET_BACKEND := $(BUILD_DIR)/test_winsock1_socket_backend.exe
WINSOCK1_SERVER_TRANSPORT := $(BUILD_DIR)/test_server_transport-winsock1.exe
WINSOCK1_SERVER_RUNTIME := $(BUILD_DIR)/test_server_runtime-winsock1.exe
WINSOCK1_SERVER_STREAMING := $(BUILD_DIR)/test_server_streaming-winsock1.exe

WINDOWS_WINSOCK1_SRCS := $(WINDOWS_DAEMON_SRCS)

WINSOCK1_SOCKET_BACKEND_SRCS := $(WINDOWS_WINSOCK1_SOCKET_BACKEND_TEST_SRCS)
WINSOCK1_SERVER_TRANSPORT_SRCS := $(WINDOWS_SERVER_TRANSPORT_TEST_SRCS)
WINSOCK1_SERVER_RUNTIME_SRCS := $(WINDOWS_SERVER_RUNTIME_TEST_SRCS)
WINSOCK1_SERVER_STREAMING_SRCS := $(WINDOWS_SERVER_STREAMING_SRCS)

WINDOWS_WINSOCK1_OBJS := $(sort $(call cpp_objs,$(WINDOWS_WINSOCK1_PROD_OBJ_DIR),$(WINDOWS_WINSOCK1_SRCS)))
WINSOCK1_SOCKET_BACKEND_OBJS := $(sort $(call cpp_objs,$(WINDOWS_WINSOCK1_TEST_OBJ_DIR),$(WINSOCK1_SOCKET_BACKEND_SRCS)))
WINSOCK1_SERVER_TRANSPORT_OBJS := $(sort $(call cpp_objs,$(WINDOWS_WINSOCK1_TEST_OBJ_DIR),$(WINSOCK1_SERVER_TRANSPORT_SRCS)))
WINSOCK1_SERVER_RUNTIME_OBJS := $(sort $(call cpp_objs,$(WINDOWS_WINSOCK1_TEST_OBJ_DIR),$(WINSOCK1_SERVER_RUNTIME_SRCS)))
WINSOCK1_SERVER_STREAMING_OBJS := $(sort $(call cpp_objs,$(WINDOWS_WINSOCK1_TEST_OBJ_DIR),$(WINSOCK1_SERVER_STREAMING_SRCS)))

WINSOCK1_TEST_TARGETS := \
	$(WINSOCK1_SOCKET_BACKEND) \
	$(WINSOCK1_SERVER_TRANSPORT) \
	$(WINSOCK1_SERVER_RUNTIME) \
	$(WINSOCK1_SERVER_STREAMING)

DEP_FILES += \
	$(WINDOWS_WINSOCK1_OBJS:.o=.d) \
	$(WINSOCK1_SOCKET_BACKEND_OBJS:.o=.d) \
	$(WINSOCK1_SERVER_TRANSPORT_OBJS:.o=.d) \
	$(WINSOCK1_SERVER_RUNTIME_OBJS:.o=.d) \
	$(WINSOCK1_SERVER_STREAMING_OBJS:.o=.d)

define run_windows_test
$1: $2
	REMOTE_EXEC_LOG=$$(TEST_LOG_LEVEL) $$(WINDOWS_TEST_RUNNER) $2
endef

define link_windows_winsock1_test
$1: $2
	mkdir -p $$(dir $$@)
	$$(WINDOWS_CXX) $$(WINDOWS_TEST_CXXFLAGS) $$(WINDOWS_LDFLAGS) -o $$@ $$^ $$(WINDOWS_WINSOCK1_LDLIBS)
endef

all-winsock1: $(WINDOWS_WINSOCK1_TARGET)

$(WINDOWS_WINSOCK1_TARGET): $(WINDOWS_WINSOCK1_OBJS)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_PROD_CXXFLAGS) $(WINDOWS_LDFLAGS) -o $@ $^ $(WINDOWS_WINSOCK1_LDLIBS)

$(WINDOWS_WINSOCK1_PROD_OBJ_DIR)/%.o: $(MAKEFILE_DIR)%.cpp
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_WINSOCK1_PROD_CPPFLAGS) $(WINDOWS_PROD_CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

$(WINDOWS_WINSOCK1_TEST_OBJ_DIR)/%.o: $(MAKEFILE_DIR)%.cpp
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_WINSOCK1_TEST_CPPFLAGS) $(WINDOWS_TEST_CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

$(eval $(call run_windows_test,test-winsock1-socket-backend,$(WINSOCK1_SOCKET_BACKEND)))
$(eval $(call link_windows_winsock1_test,$(WINSOCK1_SOCKET_BACKEND),$(WINSOCK1_SOCKET_BACKEND_OBJS)))

$(eval $(call run_windows_test,test-winsock1-server-transport,$(WINSOCK1_SERVER_TRANSPORT)))
$(eval $(call link_windows_winsock1_test,$(WINSOCK1_SERVER_TRANSPORT),$(WINSOCK1_SERVER_TRANSPORT_OBJS)))

$(eval $(call run_windows_test,test-winsock1-server-runtime,$(WINSOCK1_SERVER_RUNTIME)))
$(eval $(call link_windows_winsock1_test,$(WINSOCK1_SERVER_RUNTIME),$(WINSOCK1_SERVER_RUNTIME_OBJS)))

$(eval $(call run_windows_test,test-winsock1-server-streaming,$(WINSOCK1_SERVER_STREAMING)))
$(eval $(call link_windows_winsock1_test,$(WINSOCK1_SERVER_STREAMING),$(WINSOCK1_SERVER_STREAMING_OBJS)))

test-winsock1: $(WINSOCK1_TEST_TARGETS)
	REMOTE_EXEC_LOG=$(TEST_LOG_LEVEL) $(WINDOWS_TEST_RUNNER) $(WINSOCK1_SOCKET_BACKEND)
	REMOTE_EXEC_LOG=$(TEST_LOG_LEVEL) $(WINDOWS_TEST_RUNNER) $(WINSOCK1_SERVER_TRANSPORT)
	REMOTE_EXEC_LOG=$(TEST_LOG_LEVEL) $(WINDOWS_TEST_RUNNER) $(WINSOCK1_SERVER_RUNTIME)
	REMOTE_EXEC_LOG=$(TEST_LOG_LEVEL) $(WINDOWS_TEST_RUNNER) $(WINSOCK1_SERVER_STREAMING)

check-winsock1: all-winsock1 test-winsock1

.PHONY: all-winsock1 test-winsock1-socket-backend test-winsock1-server-transport test-winsock1-server-runtime test-winsock1-server-streaming test-winsock1 check-winsock1
