ifndef WINDOWS_GNU_MK_INCLUDED
WINDOWS_GNU_MK_INCLUDED := 1

WINDOWS_NATIVE_TOOLCHAIN := native
WINDOWS_CROSS_TOOLCHAIN := cross
WINDOWS_XP_PROFILE := xp
WINDOWS_WINSOCK1_PROFILE := winsock1

WINDOWS_TOOLCHAIN ?= $(if $(filter Windows_NT,$(OS)),$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_CROSS_TOOLCHAIN))
WINDOWS_PROFILE ?= $(WINDOWS_XP_PROFILE)

WINDOWS_COMMON_CPPFLAGS := $(COMMON_CPPFLAGS) -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE
WINDOWS_TEST_CXXFLAGS := $(TEST_CXXFLAGS)
WINDOWS_PROD_CXXFLAGS := $(PROD_CXXFLAGS)

WINDOWS_CROSS_CXX ?= i686-w64-mingw32-g++
WINDOWS_NATIVE_CXX ?= g++
WINE ?= wine

ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_CROSS_TOOLCHAIN))
WINDOWS_CXX ?= $(WINDOWS_CROSS_CXX)
WINDOWS_TOOLCHAIN_LDFLAGS_DEFAULT := -static-libgcc -static-libstdc++
WINDOWS_TOOLCHAIN_BUILD_TAG := windows-cross
ifeq ($(OS),Windows_NT)
WINDOWS_TEST_RUNNER ?=
else
WINDOWS_TEST_RUNNER ?= $(WINE)
endif
endif

ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_NATIVE_TOOLCHAIN))
ifeq ($(OS),Windows_NT)
WINDOWS_CXX ?= $(WINDOWS_NATIVE_CXX)
WINDOWS_TOOLCHAIN_LDFLAGS_DEFAULT :=
WINDOWS_TOOLCHAIN_BUILD_TAG := windows-native
WINDOWS_TEST_RUNNER ?=
else
$(error WINDOWS_TOOLCHAIN=native requires a Windows GNU host environment)
endif
endif

ifndef WINDOWS_TOOLCHAIN_BUILD_TAG
$(error unsupported WINDOWS_TOOLCHAIN '$(WINDOWS_TOOLCHAIN)')
endif

ifeq ($(WINDOWS_PROFILE),$(WINDOWS_XP_PROFILE))
WINDOWS_PROFILE_VERSION_CPPFLAGS := -DWINVER=0x0501 -D_WIN32_WINNT=0x0501
WINDOWS_PROFILE_EXTRA_CPPFLAGS :=
WINDOWS_PROFILE_LDLIBS := -lws2_32
WINDOWS_PROFILE_EXTRA_TEST_CASES :=
ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_NATIVE_TOOLCHAIN))
WINDOWS_VARIANT_BINARY_TAG := native
else
WINDOWS_VARIANT_BINARY_TAG := xp
endif
endif

ifeq ($(WINDOWS_PROFILE),$(WINDOWS_WINSOCK1_PROFILE))
WINDOWS_PROFILE_VERSION_CPPFLAGS := -DWINVER=0x0400 -D_WIN32_WINNT=0x0400
WINDOWS_PROFILE_EXTRA_CPPFLAGS := -DREMOTE_EXEC_CPP_WINSOCK1
WINDOWS_PROFILE_LDLIBS := -lwsock32
WINDOWS_PROFILE_EXTRA_TEST_CASES := WINSOCK1_SOCKET_BACKEND
ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_NATIVE_TOOLCHAIN))
WINDOWS_VARIANT_BINARY_TAG := native-winsock1
else
WINDOWS_VARIANT_BINARY_TAG := winsock1
endif
endif

ifndef WINDOWS_VARIANT_BINARY_TAG
$(error unsupported WINDOWS_PROFILE '$(WINDOWS_PROFILE)')
endif

WINDOWS_LDFLAGS ?= $(WINDOWS_TOOLCHAIN_LDFLAGS_DEFAULT)
WINDOWS_TEST_ENV := REMOTE_EXEC_LOG=$(TEST_LOG_LEVEL) $(WINDOWS_TEST_RUNNER)
WINDOWS_VARIANT_BUILD_TAG := $(WINDOWS_TOOLCHAIN_BUILD_TAG)-$(WINDOWS_PROFILE)
WINDOWS_VARIANT_PROD_OBJ_DIR := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-prod
WINDOWS_VARIANT_TEST_OBJ_DIR := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-test
WINDOWS_VARIANT_TARGET := $(BUILD_DIR)/remote-exec-daemon-cpp-$(WINDOWS_VARIANT_BINARY_TAG).exe
WINDOWS_VARIANT_PROD_CPPFLAGS := $(WINDOWS_COMMON_CPPFLAGS) $(WINDOWS_PROFILE_VERSION_CPPFLAGS) $(WINDOWS_PROFILE_EXTRA_CPPFLAGS)
WINDOWS_VARIANT_TEST_CPPFLAGS := $(WINDOWS_COMMON_CPPFLAGS) $(WINDOWS_PROFILE_VERSION_CPPFLAGS) -DREMOTE_EXEC_CPP_TESTING $(WINDOWS_PROFILE_EXTRA_CPPFLAGS)

WINDOWS_VARIANT_SRCS := $(WINDOWS_DAEMON_SRCS)
WINDOWS_VARIANT_OBJS := $(sort $(call cpp_objs,$(WINDOWS_VARIANT_PROD_OBJ_DIR),$(WINDOWS_VARIANT_SRCS)))

WINDOWS_COMMON_TEST_CASES := \
	BASIC_MUTEX \
	CONSOLE_OUTPUT \
	PATCH \
	SESSION_STORE \
	SERVER_STREAMING \
	TRANSFER \
	CONFIG \
	HTTP_REQUEST \
	SERVER_TRANSPORT \
	CONNECTION_MANAGER \
	SERVER_ROUTES_COMMON \
	SERVER_ROUTES \
	SERVER_RUNTIME \
	SANDBOX \
	PORT_TUNNEL_FRAME

WINDOWS_WINSOCK1_TEST_CASES := \
	$(WINDOWS_COMMON_TEST_CASES) \
	WINSOCK1_SOCKET_BACKEND

WINDOWS_VARIANT_TEST_CASES := $(WINDOWS_COMMON_TEST_CASES) $(WINDOWS_PROFILE_EXTRA_TEST_CASES)

WINDOWS_TEST_CASE_BASIC_MUTEX_NAME := basic-mutex
WINDOWS_TEST_CASE_BASIC_MUTEX_BASE := test_basic_mutex
WINDOWS_TEST_CASE_BASIC_MUTEX_SRCS := $(WINDOWS_BASIC_MUTEX_TEST_SRCS)

WINDOWS_TEST_CASE_CONSOLE_OUTPUT_NAME := console-output
WINDOWS_TEST_CASE_CONSOLE_OUTPUT_BASE := test_console_output
WINDOWS_TEST_CASE_CONSOLE_OUTPUT_SRCS := $(WINDOWS_CONSOLE_OUTPUT_TEST_SRCS)

WINDOWS_TEST_CASE_PATCH_NAME := patch
WINDOWS_TEST_CASE_PATCH_BASE := test_patch
WINDOWS_TEST_CASE_PATCH_SRCS := $(HOST_PATCH_SRCS)

WINDOWS_TEST_CASE_SESSION_STORE_NAME := session-store
WINDOWS_TEST_CASE_SESSION_STORE_BASE := test_session_store
WINDOWS_TEST_CASE_SESSION_STORE_SRCS := $(WINDOWS_SESSION_STORE_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_STREAMING_NAME := server-streaming
WINDOWS_TEST_CASE_SERVER_STREAMING_BASE := test_server_streaming
WINDOWS_TEST_CASE_SERVER_STREAMING_SRCS := $(WINDOWS_SERVER_STREAMING_SRCS)

WINDOWS_TEST_CASE_TRANSFER_NAME := transfer
WINDOWS_TEST_CASE_TRANSFER_BASE := test_transfer
WINDOWS_TEST_CASE_TRANSFER_SRCS := $(HOST_TRANSFER_SRCS)

WINDOWS_TEST_CASE_CONFIG_NAME := config
WINDOWS_TEST_CASE_CONFIG_BASE := test_config
WINDOWS_TEST_CASE_CONFIG_SRCS := $(HOST_CONFIG_SRCS)

WINDOWS_TEST_CASE_HTTP_REQUEST_NAME := http-request
WINDOWS_TEST_CASE_HTTP_REQUEST_BASE := test_http_request
WINDOWS_TEST_CASE_HTTP_REQUEST_SRCS := $(HOST_HTTP_REQUEST_SRCS)

WINDOWS_TEST_CASE_SERVER_TRANSPORT_NAME := server-transport
WINDOWS_TEST_CASE_SERVER_TRANSPORT_BASE := test_server_transport
WINDOWS_TEST_CASE_SERVER_TRANSPORT_SRCS := $(WINDOWS_SERVER_TRANSPORT_TEST_SRCS)

WINDOWS_TEST_CASE_CONNECTION_MANAGER_NAME := connection-manager
WINDOWS_TEST_CASE_CONNECTION_MANAGER_BASE := test_connection_manager
WINDOWS_TEST_CASE_CONNECTION_MANAGER_SRCS := $(WINDOWS_CONNECTION_MANAGER_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_ROUTES_COMMON_NAME := server-routes-common
WINDOWS_TEST_CASE_SERVER_ROUTES_COMMON_BASE := test_server_routes_common
WINDOWS_TEST_CASE_SERVER_ROUTES_COMMON_SRCS := $(WINDOWS_SERVER_ROUTES_COMMON_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_ROUTES_NAME := server-routes
WINDOWS_TEST_CASE_SERVER_ROUTES_BASE := test_server_routes
WINDOWS_TEST_CASE_SERVER_ROUTES_SRCS := $(WINDOWS_SERVER_ROUTES_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_RUNTIME_NAME := server-runtime
WINDOWS_TEST_CASE_SERVER_RUNTIME_BASE := test_server_runtime
WINDOWS_TEST_CASE_SERVER_RUNTIME_SRCS := $(WINDOWS_SERVER_RUNTIME_TEST_SRCS)

WINDOWS_TEST_CASE_SANDBOX_NAME := sandbox
WINDOWS_TEST_CASE_SANDBOX_BASE := test_sandbox
WINDOWS_TEST_CASE_SANDBOX_SRCS := $(HOST_SANDBOX_SRCS)

WINDOWS_TEST_CASE_PORT_TUNNEL_FRAME_NAME := port-tunnel-frame
WINDOWS_TEST_CASE_PORT_TUNNEL_FRAME_BASE := test_port_tunnel_frame
WINDOWS_TEST_CASE_PORT_TUNNEL_FRAME_SRCS := $(HOST_PORT_TUNNEL_FRAME_SRCS)

WINDOWS_TEST_CASE_WINSOCK1_SOCKET_BACKEND_NAME := socket-backend
WINDOWS_TEST_CASE_WINSOCK1_SOCKET_BACKEND_BASE := test_winsock1_socket_backend
WINDOWS_TEST_CASE_WINSOCK1_SOCKET_BACKEND_SRCS := $(WINDOWS_WINSOCK1_SOCKET_BACKEND_TEST_SRCS)

windows_test_case_bin = $(BUILD_DIR)/$(WINDOWS_TEST_CASE_$1_BASE)-$(WINDOWS_VARIANT_BINARY_TAG).exe
windows_test_case_phony = test-windows-$(WINDOWS_TEST_CASE_$1_NAME)

define define_windows_test_case
WINDOWS_TEST_CASE_$1_BIN := $(call windows_test_case_bin,$1)
WINDOWS_TEST_CASE_$1_OBJS := $(sort $(call cpp_objs,$(WINDOWS_VARIANT_TEST_OBJ_DIR),$(WINDOWS_TEST_CASE_$1_SRCS)))
DEP_FILES += $$(WINDOWS_TEST_CASE_$1_OBJS:.o=.d)

$(call windows_test_case_phony,$1): $$(WINDOWS_TEST_CASE_$1_BIN)
	$$(WINDOWS_TEST_ENV) $$(WINDOWS_TEST_CASE_$1_BIN)

$$(WINDOWS_TEST_CASE_$1_BIN): $$(WINDOWS_TEST_CASE_$1_OBJS)
	mkdir -p $$(dir $$@)
	$$(WINDOWS_CXX) $$(WINDOWS_TEST_CXXFLAGS) $$(WINDOWS_LDFLAGS) -o $$@ $$^ $$(WINDOWS_PROFILE_LDLIBS)
endef

$(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(eval $(call define_windows_test_case,$(test))))

WINDOWS_VARIANT_TEST_BINS := $(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(call windows_test_case_bin,$(test)))
WINDOWS_VARIANT_TEST_PHONIES := $(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(call windows_test_case_phony,$(test)))
DEP_FILES += $(WINDOWS_VARIANT_OBJS:.o=.d)

define run_windows_variant_tests
$(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(WINDOWS_TEST_ENV) $(call windows_test_case_bin,$(test))
)
endef

all-windows: $(WINDOWS_VARIANT_TARGET)

$(WINDOWS_VARIANT_TARGET): $(WINDOWS_VARIANT_OBJS)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_PROD_CXXFLAGS) $(WINDOWS_LDFLAGS) -o $@ $^ $(WINDOWS_PROFILE_LDLIBS)

$(WINDOWS_VARIANT_PROD_OBJ_DIR)/%.o: $(MAKEFILE_DIR)%.cpp
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_VARIANT_PROD_CPPFLAGS) $(WINDOWS_PROD_CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

$(WINDOWS_VARIANT_TEST_OBJ_DIR)/%.o: $(MAKEFILE_DIR)%.cpp
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_VARIANT_TEST_CPPFLAGS) $(WINDOWS_TEST_CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

test-windows: $(WINDOWS_VARIANT_TEST_BINS)
	$(run_windows_variant_tests)

check-windows: all-windows test-windows

define define_windows_variant_alias
$1:
	$$(MAKE) $2 WINDOWS_TOOLCHAIN=$3 WINDOWS_PROFILE=$4 BUILD_DIR=$$(BUILD_DIR)
endef

$(eval $(call define_windows_variant_alias,all-windows-xp,all-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_XP_PROFILE)))
$(eval $(call define_windows_variant_alias,test-windows-xp,test-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_XP_PROFILE)))
$(eval $(call define_windows_variant_alias,check-windows-xp,check-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_XP_PROFILE)))
$(eval $(call define_windows_variant_alias,all-winsock1,all-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINSOCK1_PROFILE)))
$(eval $(call define_windows_variant_alias,test-winsock1,test-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINSOCK1_PROFILE)))
$(eval $(call define_windows_variant_alias,check-winsock1,check-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINSOCK1_PROFILE)))
$(eval $(call define_windows_variant_alias,all-windows-native,all-windows,$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_XP_PROFILE)))
$(eval $(call define_windows_variant_alias,test-windows-native,test-windows,$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_XP_PROFILE)))
$(eval $(call define_windows_variant_alias,check-windows-native,check-windows,$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_XP_PROFILE)))

define define_windows_variant_test_alias
$1:
	$$(MAKE) $2 WINDOWS_TOOLCHAIN=$3 WINDOWS_PROFILE=$4 BUILD_DIR=$$(BUILD_DIR)
endef

$(foreach test,$(WINDOWS_COMMON_TEST_CASES),$(eval $(call define_windows_variant_test_alias,test-windows-xp-$(WINDOWS_TEST_CASE_$(test)_NAME),$(call windows_test_case_phony,$(test)),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_XP_PROFILE))))
$(foreach test,$(WINDOWS_WINSOCK1_TEST_CASES),$(eval $(call define_windows_variant_test_alias,test-winsock1-$(WINDOWS_TEST_CASE_$(test)_NAME),$(call windows_test_case_phony,$(test)),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINSOCK1_PROFILE))))
$(foreach test,$(WINDOWS_COMMON_TEST_CASES),$(eval $(call define_windows_variant_test_alias,test-windows-native-$(WINDOWS_TEST_CASE_$(test)_NAME),$(call windows_test_case_phony,$(test)),$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_XP_PROFILE))))

WINDOWS_XP_TEST_ALIAS_PHONIES := $(foreach test,$(WINDOWS_COMMON_TEST_CASES),test-windows-xp-$(WINDOWS_TEST_CASE_$(test)_NAME))
WINDOWS_WINSOCK1_TEST_ALIAS_PHONIES := $(foreach test,$(WINDOWS_WINSOCK1_TEST_CASES),test-winsock1-$(WINDOWS_TEST_CASE_$(test)_NAME))
WINDOWS_NATIVE_TEST_ALIAS_PHONIES := $(foreach test,$(WINDOWS_COMMON_TEST_CASES),test-windows-native-$(WINDOWS_TEST_CASE_$(test)_NAME))

.PHONY: \
	all-windows \
	test-windows \
	check-windows \
	all-windows-xp \
	test-windows-xp \
	check-windows-xp \
	all-winsock1 \
	test-winsock1 \
	check-winsock1 \
	all-windows-native \
	test-windows-native \
	check-windows-native \
	$(WINDOWS_VARIANT_TEST_PHONIES) \
	$(WINDOWS_XP_TEST_ALIAS_PHONIES) \
	$(WINDOWS_WINSOCK1_TEST_ALIAS_PHONIES) \
	$(WINDOWS_NATIVE_TEST_ALIAS_PHONIES)

endif
