ifndef WINDOWS_GNU_MK_INCLUDED
WINDOWS_GNU_MK_INCLUDED := 1

WINDOWS_NATIVE_TOOLCHAIN := native
WINDOWS_CROSS_TOOLCHAIN := cross

WINDOWS_WINVER_NT4 := 0x0400
WINDOWS_WINVER_2000 := 0x0500
WINDOWS_WINVER_XP := 0x0501

WINDOWS_WINSOCK1 := 1
WINDOWS_WINSOCK2 := 2

WINDOWS_TOOLCHAIN ?= $(if $(filter Windows_NT,$(OS)),$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_CROSS_TOOLCHAIN))
WINDOWS_WINVER ?= $(WINDOWS_WINVER_XP)
WINDOWS_WIN32_WINNT ?= $(WINDOWS_WINVER)
WINDOWS_WINSOCK_VERSION ?= $(WINDOWS_WINSOCK2)
WINDOWS_WINPTY ?= auto

WINDOWS_COMMON_CPPFLAGS := $(COMMON_CPPFLAGS) -DWIN32_LEAN_AND_MEAN -DUNICODE -D_UNICODE
WINDOWS_TEST_CXXFLAGS := $(TEST_CXXFLAGS)
WINDOWS_PROD_CXXFLAGS := $(PROD_CXXFLAGS)

WINDOWS_CROSS_CXX ?= i686-w64-mingw32-g++
WINDOWS_NATIVE_CXX ?= g++
WINE ?= wine

ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_CROSS_TOOLCHAIN))
WINDOWS_CXX ?= $(WINDOWS_CROSS_CXX)
WINDOWS_TOOLCHAIN_LDFLAGS_DEFAULT := -static-libgcc -static-libstdc++
WINDOWS_TOOLCHAIN_BUILD_TAG := windows-cross
ifeq ($(OS),Windows_NT)
WINDOWS_TEST_RUNNER ?=
else
WINDOWS_TEST_RUNNER ?= $(WINE)
endif
endif

ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_NATIVE_TOOLCHAIN))
ifeq ($(OS),Windows_NT)
WINDOWS_CXX ?= $(WINDOWS_NATIVE_CXX)
WINDOWS_TOOLCHAIN_LDFLAGS_DEFAULT :=
WINDOWS_TOOLCHAIN_BUILD_TAG := windows-native
WINDOWS_TEST_RUNNER ?=
else
$(error WINDOWS_TOOLCHAIN=native requires a Windows GNU host environment)
endif
endif

ifndef WINDOWS_TOOLCHAIN_BUILD_TAG
$(error unsupported WINDOWS_TOOLCHAIN '$(WINDOWS_TOOLCHAIN)')
endif

ifeq ($(filter $(WINDOWS_WINSOCK_VERSION),$(WINDOWS_WINSOCK1) $(WINDOWS_WINSOCK2)),)
$(error unsupported WINDOWS_WINSOCK_VERSION '$(WINDOWS_WINSOCK_VERSION)'; use 1 or 2)
endif

ifeq ($(filter $(WINDOWS_WINPTY),auto on off),)
$(error unsupported WINDOWS_WINPTY '$(WINDOWS_WINPTY)'; use auto, on, or off)
endif

WINDOWS_WINVER_HEX_TAG := $(patsubst 0x%,%,$(patsubst 0X%,%,$(WINDOWS_WINVER)))
WINDOWS_WINVER_LABEL := $(if $(filter $(WINDOWS_WINVER),$(WINDOWS_WINVER_NT4)),nt4,$(if $(filter $(WINDOWS_WINVER),$(WINDOWS_WINVER_2000)),2000,$(if $(filter $(WINDOWS_WINVER),$(WINDOWS_WINVER_XP)),xp,winver$(WINDOWS_WINVER_HEX_TAG))))
WINDOWS_WS_TAG := ws$(WINDOWS_WINSOCK_VERSION)
WINDOWS_VARIANT_AXIS_TAG := $(WINDOWS_WINVER_LABEL)-$(WINDOWS_WS_TAG)

WINDOWS_VARIANT_VERSION_CPPFLAGS := -DWINVER=$(WINDOWS_WINVER) -D_WIN32_WINNT=$(WINDOWS_WIN32_WINNT)
WINDOWS_VARIANT_EXTRA_CPPFLAGS :=
WINDOWS_VARIANT_LDLIBS :=
WINDOWS_VARIANT_EXTRA_TEST_CASES :=
WINDOWS_VARIANT_BUILD_ARTIFACTS :=
WINDOWS_VARIANT_RUNTIME_ARTIFACTS :=

ifeq ($(WINDOWS_WINPTY),on)
WINDOWS_WINPTY_ENABLED := 1
endif
ifeq ($(WINDOWS_WINPTY),off)
WINDOWS_WINPTY_ENABLED := 0
endif
ifndef WINDOWS_WINPTY_ENABLED
ifeq ($(WINDOWS_WINSOCK_VERSION),$(WINDOWS_WINSOCK2))
ifeq ($(WINDOWS_WINVER),$(WINDOWS_WINVER_XP))
WINDOWS_WINPTY_ENABLED := 1
else
WINDOWS_WINPTY_ENABLED := 0
endif
else
WINDOWS_WINPTY_ENABLED := 0
endif
endif

WINDOWS_VARIANT_BUILD_TAG := $(WINDOWS_TOOLCHAIN_BUILD_TAG)-winver$(WINDOWS_WINVER_HEX_TAG)-$(WINDOWS_WS_TAG)

WINPTY_VERSION_HEADER := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-winpty/gen/GenVersion.h
WINPTY_OBJ_DIR := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-winpty
WINPTY_LIB_OBJ_DIR := $(WINPTY_OBJ_DIR)/libwinpty
WINPTY_AGENT_OBJ_DIR := $(WINPTY_OBJ_DIR)/agent
WINPTY_STATIC_LIB := $(WINPTY_OBJ_DIR)/libwinpty.a
WINPTY_AGENT_EXE := $(BUILD_DIR)/winpty-agent.exe
WINPTY_LIB_OBJECTS := $(addprefix $(WINPTY_LIB_OBJ_DIR)/,$(addsuffix .o,$(WINPTY_LIBWINPTY_STEMS)))
WINPTY_AGENT_OBJECTS := $(addprefix $(WINPTY_AGENT_OBJ_DIR)/,$(addsuffix .o,$(WINPTY_AGENT_STEMS)))
WINDOWS_AR ?= $(shell $(WINDOWS_CXX) -print-prog-name=ar)

ifeq ($(WINDOWS_WINSOCK_VERSION),$(WINDOWS_WINSOCK1))
WINDOWS_VARIANT_EXTRA_CPPFLAGS += -DREMOTE_EXEC_CPP_WINSOCK1
WINDOWS_VARIANT_LDLIBS += -lwsock32
WINDOWS_VARIANT_EXTRA_TEST_CASES += WINSOCK1_SOCKET_BACKEND
else
WINDOWS_VARIANT_LDLIBS += -lws2_32
ifeq ($(WINDOWS_WINPTY_ENABLED),1)
WINDOWS_VARIANT_EXTRA_CPPFLAGS += -DREMOTE_EXEC_CPP_HAS_WINPTY -DWINPTY_STATIC -I$(WINPTY_VENDOR_SRC_DIR)/include -I$(WINPTY_VENDOR_SRC_DIR) -I$(dir $(WINPTY_VERSION_HEADER))
WINDOWS_VARIANT_LDLIBS += $(WINPTY_STATIC_LIB) -ladvapi32 -lshell32 -luser32
WINDOWS_VARIANT_BUILD_ARTIFACTS += $(WINPTY_STATIC_LIB)
WINDOWS_VARIANT_RUNTIME_ARTIFACTS += $(WINPTY_AGENT_EXE)
endif
endif

ifeq ($(WINDOWS_TOOLCHAIN),$(WINDOWS_NATIVE_TOOLCHAIN))
WINDOWS_VARIANT_BINARY_TAG := native-$(WINDOWS_VARIANT_AXIS_TAG)
else
WINDOWS_VARIANT_BINARY_TAG := $(WINDOWS_VARIANT_AXIS_TAG)
endif

WINDOWS_LDFLAGS ?= $(WINDOWS_TOOLCHAIN_LDFLAGS_DEFAULT)
WINDOWS_TEST_ENV := REMOTE_EXEC_LOG=$(TEST_LOG_LEVEL) $(WINDOWS_TEST_RUNNER)
WINDOWS_VARIANT_PROD_OBJ_DIR := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-prod
WINDOWS_VARIANT_TEST_OBJ_DIR := $(OBJ_DIR)/$(WINDOWS_VARIANT_BUILD_TAG)-test
WINDOWS_VARIANT_TARGET := $(BUILD_DIR)/remote-exec-daemon-cpp-$(WINDOWS_VARIANT_BINARY_TAG).exe
WINDOWS_VARIANT_PROD_CPPFLAGS := $(WINDOWS_COMMON_CPPFLAGS) $(WINDOWS_VARIANT_VERSION_CPPFLAGS) $(WINDOWS_VARIANT_EXTRA_CPPFLAGS)
WINDOWS_VARIANT_TEST_CPPFLAGS := $(WINDOWS_COMMON_CPPFLAGS) $(WINDOWS_VARIANT_VERSION_CPPFLAGS) -DREMOTE_EXEC_CPP_TESTING $(WINDOWS_VARIANT_EXTRA_CPPFLAGS)

DEP_FILES += $(WINPTY_LIB_OBJECTS:.o=.d) $(WINPTY_AGENT_OBJECTS:.o=.d)

WINDOWS_VARIANT_SRCS := $(WINDOWS_DAEMON_SRCS)
WINDOWS_VARIANT_OBJS := $(sort $(call cpp_objs,$(WINDOWS_VARIANT_PROD_OBJ_DIR),$(WINDOWS_VARIANT_SRCS)))

WINDOWS_COMMON_TEST_CASES := \
	BASIC_MUTEX \
	CONSOLE_OUTPUT \
	PATCH \
	SESSION_STORE \
	SERVER_STREAMING \
	TRANSFER \
	CONFIG \
	HTTP_REQUEST \
	SERVER_TRANSPORT \
	CONNECTION_MANAGER \
	SERVER_ROUTES_COMMON \
	SERVER_ROUTES \
	SERVER_RUNTIME \
	SANDBOX \
	PORT_TUNNEL_FRAME

WINDOWS_VARIANT_TEST_CASES := $(WINDOWS_COMMON_TEST_CASES) $(WINDOWS_VARIANT_EXTRA_TEST_CASES)

WINDOWS_TEST_CASE_BASIC_MUTEX_NAME := basic-mutex
WINDOWS_TEST_CASE_BASIC_MUTEX_BASE := test_basic_mutex
WINDOWS_TEST_CASE_BASIC_MUTEX_SRCS := $(WINDOWS_BASIC_MUTEX_TEST_SRCS)

WINDOWS_TEST_CASE_CONSOLE_OUTPUT_NAME := console-output
WINDOWS_TEST_CASE_CONSOLE_OUTPUT_BASE := test_console_output
WINDOWS_TEST_CASE_CONSOLE_OUTPUT_SRCS := $(WINDOWS_CONSOLE_OUTPUT_TEST_SRCS)

WINDOWS_TEST_CASE_PATCH_NAME := patch
WINDOWS_TEST_CASE_PATCH_BASE := test_patch
WINDOWS_TEST_CASE_PATCH_SRCS := $(HOST_PATCH_SRCS)

WINDOWS_TEST_CASE_SESSION_STORE_NAME := session-store
WINDOWS_TEST_CASE_SESSION_STORE_BASE := test_session_store
WINDOWS_TEST_CASE_SESSION_STORE_SRCS := $(WINDOWS_SESSION_STORE_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_STREAMING_NAME := server-streaming
WINDOWS_TEST_CASE_SERVER_STREAMING_BASE := test_server_streaming
WINDOWS_TEST_CASE_SERVER_STREAMING_SRCS := $(WINDOWS_SERVER_STREAMING_SRCS)

WINDOWS_TEST_CASE_TRANSFER_NAME := transfer
WINDOWS_TEST_CASE_TRANSFER_BASE := test_transfer
WINDOWS_TEST_CASE_TRANSFER_SRCS := $(HOST_TRANSFER_SRCS)

WINDOWS_TEST_CASE_CONFIG_NAME := config
WINDOWS_TEST_CASE_CONFIG_BASE := test_config
WINDOWS_TEST_CASE_CONFIG_SRCS := $(HOST_CONFIG_SRCS)

WINDOWS_TEST_CASE_HTTP_REQUEST_NAME := http-request
WINDOWS_TEST_CASE_HTTP_REQUEST_BASE := test_http_request
WINDOWS_TEST_CASE_HTTP_REQUEST_SRCS := $(HOST_HTTP_REQUEST_SRCS)

WINDOWS_TEST_CASE_SERVER_TRANSPORT_NAME := server-transport
WINDOWS_TEST_CASE_SERVER_TRANSPORT_BASE := test_server_transport
WINDOWS_TEST_CASE_SERVER_TRANSPORT_SRCS := $(WINDOWS_SERVER_TRANSPORT_TEST_SRCS)

WINDOWS_TEST_CASE_CONNECTION_MANAGER_NAME := connection-manager
WINDOWS_TEST_CASE_CONNECTION_MANAGER_BASE := test_connection_manager
WINDOWS_TEST_CASE_CONNECTION_MANAGER_SRCS := $(WINDOWS_CONNECTION_MANAGER_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_ROUTES_COMMON_NAME := server-routes-common
WINDOWS_TEST_CASE_SERVER_ROUTES_COMMON_BASE := test_server_routes_common
WINDOWS_TEST_CASE_SERVER_ROUTES_COMMON_SRCS := $(WINDOWS_SERVER_ROUTES_COMMON_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_ROUTES_NAME := server-routes
WINDOWS_TEST_CASE_SERVER_ROUTES_BASE := test_server_routes
WINDOWS_TEST_CASE_SERVER_ROUTES_SRCS := $(WINDOWS_SERVER_ROUTES_TEST_SRCS)

WINDOWS_TEST_CASE_SERVER_RUNTIME_NAME := server-runtime
WINDOWS_TEST_CASE_SERVER_RUNTIME_BASE := test_server_runtime
WINDOWS_TEST_CASE_SERVER_RUNTIME_SRCS := $(WINDOWS_SERVER_RUNTIME_TEST_SRCS)

WINDOWS_TEST_CASE_SANDBOX_NAME := sandbox
WINDOWS_TEST_CASE_SANDBOX_BASE := test_sandbox
WINDOWS_TEST_CASE_SANDBOX_SRCS := $(HOST_SANDBOX_SRCS)

WINDOWS_TEST_CASE_PORT_TUNNEL_FRAME_NAME := port-tunnel-frame
WINDOWS_TEST_CASE_PORT_TUNNEL_FRAME_BASE := test_port_tunnel_frame
WINDOWS_TEST_CASE_PORT_TUNNEL_FRAME_SRCS := $(HOST_PORT_TUNNEL_FRAME_SRCS)

WINDOWS_TEST_CASE_WINSOCK1_SOCKET_BACKEND_NAME := winsock1-socket-backend
WINDOWS_TEST_CASE_WINSOCK1_SOCKET_BACKEND_BASE := test_winsock1_socket_backend
WINDOWS_TEST_CASE_WINSOCK1_SOCKET_BACKEND_SRCS := $(WINDOWS_WINSOCK1_SOCKET_BACKEND_TEST_SRCS)

windows_test_case_bin = $(BUILD_DIR)/$(WINDOWS_TEST_CASE_$1_BASE)-$(WINDOWS_VARIANT_BINARY_TAG).exe
windows_test_case_phony = test-windows-$(WINDOWS_TEST_CASE_$1_NAME)

define define_windows_test_case
WINDOWS_TEST_CASE_$1_BIN := $(call windows_test_case_bin,$1)
WINDOWS_TEST_CASE_$1_OBJS := $(sort $(call cpp_objs,$(WINDOWS_VARIANT_TEST_OBJ_DIR),$(WINDOWS_TEST_CASE_$1_SRCS)))
DEP_FILES += $$(WINDOWS_TEST_CASE_$1_OBJS:.o=.d)

$(call windows_test_case_phony,$1): $$(WINDOWS_TEST_CASE_$1_BIN) $(WINDOWS_VARIANT_RUNTIME_ARTIFACTS)
	$$(WINDOWS_TEST_ENV) $$(WINDOWS_TEST_CASE_$1_BIN)

$$(WINDOWS_TEST_CASE_$1_BIN): $$(WINDOWS_TEST_CASE_$1_OBJS) $(WINDOWS_VARIANT_BUILD_ARTIFACTS) $(WINDOWS_VARIANT_RUNTIME_ARTIFACTS)
	mkdir -p $$(dir $$@)
	$$(WINDOWS_CXX) $$(WINDOWS_TEST_CXXFLAGS) $$(WINDOWS_LDFLAGS) -o $$@ $$(WINDOWS_TEST_CASE_$1_OBJS) $$(WINDOWS_VARIANT_LDLIBS)
endef

$(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(eval $(call define_windows_test_case,$(test))))

WINDOWS_VARIANT_TEST_BINS := $(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(call windows_test_case_bin,$(test)))
WINDOWS_VARIANT_TEST_PHONIES := $(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(call windows_test_case_phony,$(test)))
DEP_FILES += $(WINDOWS_VARIANT_OBJS:.o=.d)

define run_windows_variant_tests
$(foreach test,$(WINDOWS_VARIANT_TEST_CASES),$(WINDOWS_TEST_ENV) $(call windows_test_case_bin,$(test))
)
endef

all-windows: $(WINDOWS_VARIANT_TARGET)

$(WINDOWS_VARIANT_TARGET): $(WINDOWS_VARIANT_OBJS) $(WINDOWS_VARIANT_BUILD_ARTIFACTS) $(WINDOWS_VARIANT_RUNTIME_ARTIFACTS)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_PROD_CXXFLAGS) $(WINDOWS_LDFLAGS) -o $@ $(WINDOWS_VARIANT_OBJS) $(WINDOWS_VARIANT_LDLIBS)

$(WINPTY_VERSION_HEADER): $(WINPTY_VENDOR_DIR)/VERSION.txt
	mkdir -p $(dir $@)
	printf '%s\n' '// AUTO-GENERATED BY mk/windows-gnu.mk' > $@
	printf 'const char GenVersion_Version[] = "%s";\n' "$$(tr -d '\r\n' < $<)" >> $@
	printf 'const char GenVersion_Commit[] = "none";\n' >> $@

$(WINPTY_LIB_OBJ_DIR)/%.o: $(WINPTY_VENDOR_SRC_DIR)/%.cc $(WINPTY_VERSION_HEADER)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_VARIANT_VERSION_CPPFLAGS) -DREMOTE_EXEC_CPP_HAS_WINPTY -DWINPTY_STATIC -DNOMINMAX -DUNICODE -D_UNICODE $(WINDOWS_PROD_CXXFLAGS) $(DEPFLAGS) -I$(WINPTY_VENDOR_SRC_DIR)/include -I$(WINPTY_VENDOR_SRC_DIR) -I$(dir $(WINPTY_VERSION_HEADER)) -c -o $@ $<

$(WINPTY_AGENT_OBJ_DIR)/%.o: $(WINPTY_VENDOR_SRC_DIR)/%.cc $(WINPTY_VERSION_HEADER)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_VARIANT_VERSION_CPPFLAGS) -DREMOTE_EXEC_CPP_HAS_WINPTY -DWINPTY_AGENT_ASSERT -DNOMINMAX -DUNICODE -D_UNICODE $(WINDOWS_PROD_CXXFLAGS) $(DEPFLAGS) -I$(WINPTY_VENDOR_SRC_DIR)/include -I$(WINPTY_VENDOR_SRC_DIR) -I$(dir $(WINPTY_VERSION_HEADER)) -c -o $@ $<

$(WINPTY_STATIC_LIB): $(WINPTY_LIB_OBJECTS)
	mkdir -p $(dir $@)
	$(WINDOWS_AR) rcs $@ $^

$(WINPTY_AGENT_EXE): $(WINPTY_AGENT_OBJECTS)
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_PROD_CXXFLAGS) $(WINDOWS_LDFLAGS) -o $@ $^ -ladvapi32 -lshell32 -luser32

$(WINDOWS_VARIANT_PROD_OBJ_DIR)/%.o: $(MAKEFILE_DIR)%.cpp
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_VARIANT_PROD_CPPFLAGS) $(WINDOWS_PROD_CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

$(WINDOWS_VARIANT_TEST_OBJ_DIR)/%.o: $(MAKEFILE_DIR)%.cpp
	mkdir -p $(dir $@)
	$(WINDOWS_CXX) $(WINDOWS_VARIANT_TEST_CPPFLAGS) $(WINDOWS_TEST_CXXFLAGS) $(DEPFLAGS) -c -o $@ $<

test-windows: $(WINDOWS_VARIANT_TEST_BINS)
	$(run_windows_variant_tests)

check-windows: all-windows test-windows

define define_windows_variant_alias
$1:
	$$(MAKE) $2 WINDOWS_TOOLCHAIN=$3 WINDOWS_WINVER=$4 WINDOWS_WIN32_WINNT=$5 WINDOWS_WINSOCK_VERSION=$6 BUILD_DIR=$$(BUILD_DIR)
endef

$(eval $(call define_windows_variant_alias,all-windows-nt4-ws1,all-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK1)))
$(eval $(call define_windows_variant_alias,test-windows-nt4-ws1,test-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK1)))
$(eval $(call define_windows_variant_alias,check-windows-nt4-ws1,check-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK1)))

$(eval $(call define_windows_variant_alias,all-windows-2000,all-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_2000),$(WINDOWS_WINVER_2000),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,test-windows-2000,test-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_2000),$(WINDOWS_WINVER_2000),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,check-windows-2000,check-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_2000),$(WINDOWS_WINVER_2000),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,all-windows-2000-ws2,all-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_2000),$(WINDOWS_WINVER_2000),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,test-windows-2000-ws2,test-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_2000),$(WINDOWS_WINVER_2000),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,check-windows-2000-ws2,check-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_2000),$(WINDOWS_WINVER_2000),$(WINDOWS_WINSOCK2)))

$(eval $(call define_windows_variant_alias,all-windows-xp,all-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,test-windows-xp,test-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,check-windows-xp,check-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,all-windows-xp-ws2,all-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,test-windows-xp-ws2,test-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,check-windows-xp-ws2,check-windows,$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2)))

$(eval $(call define_windows_variant_alias,all-windows-native,all-windows,$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,test-windows-native,test-windows,$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2)))
$(eval $(call define_windows_variant_alias,check-windows-native,check-windows,$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2)))

define define_windows_variant_test_alias
$1:
	$$(MAKE) $2 WINDOWS_TOOLCHAIN=$3 WINDOWS_WINVER=$4 WINDOWS_WIN32_WINNT=$5 WINDOWS_WINSOCK_VERSION=$6 BUILD_DIR=$$(BUILD_DIR)
endef

$(foreach test,$(WINDOWS_COMMON_TEST_CASES),$(eval $(call define_windows_variant_test_alias,test-windows-xp-$(WINDOWS_TEST_CASE_$(test)_NAME),$(call windows_test_case_phony,$(test)),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2))))
$(foreach test,$(WINDOWS_COMMON_TEST_CASES),$(eval $(call define_windows_variant_test_alias,test-windows-2000-$(WINDOWS_TEST_CASE_$(test)_NAME),$(call windows_test_case_phony,$(test)),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_2000),$(WINDOWS_WINVER_2000),$(WINDOWS_WINSOCK2))))
$(foreach test,$(WINDOWS_COMMON_TEST_CASES),$(eval $(call define_windows_variant_test_alias,test-windows-native-$(WINDOWS_TEST_CASE_$(test)_NAME),$(call windows_test_case_phony,$(test)),$(WINDOWS_NATIVE_TOOLCHAIN),$(WINDOWS_WINVER_XP),$(WINDOWS_WINVER_XP),$(WINDOWS_WINSOCK2))))
$(foreach test,$(WINDOWS_COMMON_TEST_CASES) WINSOCK1_SOCKET_BACKEND,$(eval $(call define_windows_variant_test_alias,test-windows-nt4-ws1-$(WINDOWS_TEST_CASE_$(test)_NAME),$(call windows_test_case_phony,$(test)),$(WINDOWS_CROSS_TOOLCHAIN),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINVER_NT4),$(WINDOWS_WINSOCK1))))

WINDOWS_XP_TEST_ALIAS_PHONIES := $(foreach test,$(WINDOWS_COMMON_TEST_CASES),test-windows-xp-$(WINDOWS_TEST_CASE_$(test)_NAME))
WINDOWS_2000_TEST_ALIAS_PHONIES := $(foreach test,$(WINDOWS_COMMON_TEST_CASES),test-windows-2000-$(WINDOWS_TEST_CASE_$(test)_NAME))
WINDOWS_NT4_WS1_TEST_ALIAS_PHONIES := $(foreach test,$(WINDOWS_COMMON_TEST_CASES) WINSOCK1_SOCKET_BACKEND,test-windows-nt4-ws1-$(WINDOWS_TEST_CASE_$(test)_NAME))
WINDOWS_NATIVE_TEST_ALIAS_PHONIES := $(foreach test,$(WINDOWS_COMMON_TEST_CASES),test-windows-native-$(WINDOWS_TEST_CASE_$(test)_NAME))

.PHONY: \
	all-windows \
	test-windows \
	check-windows \
	all-windows-nt4-ws1 \
	test-windows-nt4-ws1 \
	check-windows-nt4-ws1 \
	all-windows-2000 \
	test-windows-2000 \
	check-windows-2000 \
	all-windows-2000-ws2 \
	test-windows-2000-ws2 \
	check-windows-2000-ws2 \
	all-windows-xp \
	test-windows-xp \
	check-windows-xp \
	all-windows-xp-ws2 \
	test-windows-xp-ws2 \
	check-windows-xp-ws2 \
	all-windows-native \
	test-windows-native \
	check-windows-native \
	$(WINDOWS_VARIANT_TEST_PHONIES) \
	$(WINDOWS_XP_TEST_ALIAS_PHONIES) \
	$(WINDOWS_2000_TEST_ALIAS_PHONIES) \
	$(WINDOWS_NT4_WS1_TEST_ALIAS_PHONIES) \
	$(WINDOWS_NATIVE_TEST_ALIAS_PHONIES)

endif
